### ISSUE TITLE
Request: DreamHost DNS

### ISSUE THREAD

**Issue by EZarnosky** [qdm12/ddns-updater#1]
Any chance of adding DreamHost DNS to your updater? There are a lot of small scripts out there, but they provide no GUI nor are there any Docker Containers.

DreamHost DNS - https://help.dreamhost.com/hc/en-us/articles/215413857-DreamHost-DNS-overview
Perl version - https://github.com/jhlange/dreamapi/tree/master/dreamdns
Bash version - https://github.com/pissedoffadmins/dh-dyndns

Thanks

**Comment by qdm12** [comment]
I'll work on it this weekend, it should be done by Monday! Let me know if you have any other suggestion!

**Comment by EZarnosky** [comment]
That's awesome. If you need any testing let me know, I should be around this weekend :)

**Comment by qdm12** [comment]
A few questions because I don't have an account on Dreamhost 😄 

Could you try the following HTTP URLs (modify the values in capitals) in your browser and post what they respond (**hide sensitive information**)

1.  List records

```
https://api.dreamhost.com/?key=YOURAPIKEY&format=json&type=A&cmd=dns-list_records
```

2. Delete record

```
https://api.dreamhost.com/?key=YOURAPIKEY&format=json&cmd=dns-del_record&record=YOURDOMAIN&type=A&value=127.0.0.1
```

3. Add record

```
https://api.dreamhost.com/?key=YOURAPIKEY&format=json&cmd=dns-add_record&record=YOURDOMAIN&type=A&value=127.0.0.1
```

Also:

4. Do you use IPv6 or are you ok to stick with IPv4?
5. Does DreamHost support subdomain A records? It does not seem to have an API call for that 😞

**Comment by qdm12** [comment]
Thanks! I am still working on it, you can track my commits [here](https://github.com/qdm12/ddns-updater/commits/dreamhost), I may finish tomorrow as I have a busy day ! You will then have to test it to see if it works!

**Comment by EZarnosky** [comment]
Your efforts are greatly appreciated sir. If you need anything else for testing, let me know.

**Comment by qdm12** [comment]
It should be done now, I just need some testing 👍 
Check the Docker logs with `docker logs -f ddns` or the web ui for errors it would show.
As there are many HTTP exchanges (list, delete, add) with Dreamhost, it's likely to fail at some point I think.

Also note that the password field is your API key in this case.

**Comment by qdm12** [comment]
I'll close the issue for now, feel free to re-open it when you have time to test it and if it does not work, thanks !

**Comment by qdm12** [comment]
Hi @EZarnosky, I have reworked the image a lot recently, have you had time to test Dreamhost? Is there anything not working? Thanks !
