### ISSUE TITLE
OVH support

### ISSUE THREAD

**Issue by MGoeppl** [qdm12/ddns-updater#111]
1. What's the feature?

New DNS Provider

2. Why do you need this feature?

To update my DDNS sites. 

3. Extra information?

https://docs.ovh.com/gb/en/domains/hosting_dynhost/

**Comment by qdm12** [comment]
Hey @MGoeppl sorry for the long delay

I have an image with docker tag `:ovh` can you please try it using [this readme](https://github.com/qdm12/ddns-updater/tree/ovh)?

Also, with OVH you can only specify a subdomain and use the domain `mypersonaldomain.ovh` right?

Thanks and thanks for your patience!

**Comment by arnogues** [comment]
mypersonaldomain.ovh can't be change why ? it's always mypersonaldomain.ovh ? 
It's can't be  arnaudgueras.ovh ?

**Comment by qdm12** [comment]
Oh yes totally. Can you perhaps answer the question

> Also, with OVH you can only specify a subdomain and use the domain mypersonaldomain.ovh right?

That's why i left it like that as it wasn't clear to me from their docs.
