### ISSUE TITLE
Bug: ...

### ISSUE THREAD

**Issue by BitNin** [qdm12/ddns-updater#113]
Godaddy invalid key format - wrong length for first regex capture group.  Expects 10-14 chars before the "_" but my key from GoDaddy is 8_22.

1. Is this urgent?

    - [ ] Yes
    - [x] No

2. What DNS service provider(s) are you using?

    - [ ] Cloudflare
    - [ ] DDNSS.de
    - [ ] DonDominio
    - [ ] DNSOMatic
    - [ ] DNSPod
    - [ ] Dreamhost
    - [ ] DuckDNS
    - [ ] DynDNS
    - [x] GoDaddy
    - [ ] Google
    - [ ] He.net
    - [ ] Infomaniak
    - [ ] Namecheap
    - [ ] NoIP

3. What's the version of the program?

Running version latest built on 2020-10-25T16:48:00Z (commit 3047c83)

4. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information

GoDaddy keys generated in prod for me look like this:

UyxnD4Q8_QdzYUDQ3Utx3fAJ6lmbDSP

The regex.go code for the godaddy key matcher is _(`^[A-Za-z0-9]{10,14}\_[A-Za-z0-9]{22}$`)_ so it throws an invalid key format error.  If I pad it, or use a key generated for ote it will start fine.  Obviously it won't update anything since it can't.

ote key example:  3mM44UbC89V5ai_EbXGzMnAMZxnmLsiw1ag2m

I've generated a dozen keys just to see if the length would change in prod, but it does not.

Configuration file (**remove your credentials!**):

```json
{
    "settings": [
        {
            "provider": "godaddy",
            "domain": "acme.com",
            "host": "*",
            "ip_method": "opendns",
            "delay": 300,
            "key": "UyxnD4Q8_QdzYUDQ3Utx3fAJ6lmbDSP",
            "secret": "QPsxhAr4rfjxAwl2YgaLGP"
        }
    ]
}
```
Host OS:

Docker on Ubuntu using docker-compose and traefik reverse proxy.

**Comment by qdm12** [comment]
Thanks for reporting the issue! It now accepts {8-14}_{22} characters for Godaddy key. Let me know if it doesn't work still.

**Comment by BitNin** [comment]
It now works, thank you!  I'm having an issue with authentication despite the curl working correctly but I'll figure it out or I'll submit a new one.

Just want to add - thank you for your development on this!

**Comment by qdm12** [comment]
That may be related to #91 I still don't know why it stopped working. What's your curl command (and hide creds)?
