### ISSUE TITLE
Feature request: Add Strato.de as provider

### ISSUE THREAD

**Issue by Hamster-0815** [qdm12/ddns-updater#116]
hello
i would like to use stratos ddns.

Strato uses the "DynDNS v2" protocol from dyndns.org
 
• Server: https://dyndns.strato.com/nic/update
• Host: The domain or subdomain to be redirected (e.g .: meinpc.wunschname.de)
• User: A domain from your package (e.g .: desiredname.de)
• Password: your Dynamic DNS password, which you can assign in the STRATO customer login

example of url-update:
https://ihredomain.de:DynDNS-Passwort@dyndns.strato.com/nic/update?hostname=subdomain.ihredomain.de&myip=192.XXX.X.X,2003:8106:1234:5678:abcd:ef01:2345:6789

strato.de help:
https://www.strato.de/faq/domains/so-einfach-richten-sie-dyndns-fuer-ihre-domains-ein/ (DE better)
https://www.strato.com/faq/en_us/domain/this-is-how-easy-it-is-to-set-up-dyndns-for-your-domains/ (EN)

thank you for the effort

**Comment by qdm12** [comment]
Can you please try the image with docker tag `:strado`? Thanks!

A few questions for you:

1. Can you use wildcard subdomains `*`? (I assume not)
1. Can you update your ip without specifying `myip` in the URL? (I assumed yes, but would like to be sure on that)

**Comment by Hamster-0815** [comment]
tag is :strato ;)

>1. Can you use wildcard subdomains *? (I assume not)

no wildcard are not allowed.

>2. Can you update your ip without specifying myip in the URL? (I assumed yes, but would like to be sure on that)

yes that works! then the ip is used by the sender-ip


config:
>{
    "settings": [
        {
            "provider": "strato",
                "domain":       "cgwhs.de",
                "host":         "nn",
                "username":     "cgwhs.de",
                "password":     "*********"
        }
    ]
}


log:
> ERROR   Get "https://cgwhs.de:***@dydns.strato.com/nic/update?hostname=nn.cgwhs.de&myip=********": dial tcp: lookup dydns.strato.com on 8.8.8.8:53: no such host

you use :  @dydns.strato.com
it should: @dyndns.strato.com    (n)

when I use the link in the browser it works with the dyndns

**Comment by qdm12** [comment]
Alright thanks! I fixed these up, can you pull and try again with :strato (give it a few minutes to build on Github actions)? Thanks!

**Comment by Hamster-0815** [comment]
really nice it works!
no error in logs and "Update status" : Success 
thank you

**Comment by qdm12** [comment]
Cool! I merged it the main code base so you can now use it on the Docker image with no tag or `:latest` tag. Enjoy!
