### ISSUE TITLE
Feature request: send e-mail notification upon IP change

### ISSUE THREAD

**Issue by bcurran3** [qdm12/ddns-updater#118]
1. What's the feature?

Configurable ability to send an notification upon IP change. E-mail would be my first choice many options will appeal to many people. (Gotify, Slack, etc. etc.)

2. Why do you need this feature?

I don't check my public IP much, it rarely changes (once or twice a year at most).

3. Extra information?

**Comment by qdm12** [comment]
Use shoutrrr with `SHOUTRRR_ADDRESSES` to do so.

see https://containrrr.dev/shoutrrr/v0.4/services/email/
