### ISSUE TITLE
Support selfhost.de

### ISSUE THREAD

**Issue by Frepke** [qdm12/ddns-updater#120]
Can you add https://selfhost.de/ to the list?

Why? I'm using it 😄

**Comment by qdm12** [comment]
Hey Frepke!

Can you please send me (you can use [postman](https://www.postman.com/downloads/)) the message (and status code ideally) you get from:

- https://yourusername:yourpassword@carol.selfhost.de/nic/update?hostname=somegarbagedomainyoudonthave.com
- https://yourusername:yourpassword@carol.selfhost.de/nic/update?hostname=yourdomain.com&myip=garbage
- https://yourusername:yourpassword@carol.selfhost.de/nic/update?hostname=yourdomain.com

So I can configure it for all possible responses. Thanks!

**Comment by Frepke** [comment]
Thanks for adding selfhost.de,

Below are the messages and status codes.

*   [https://yourusername:yourpassword@carol.selfhost.de/nic/update?hostname=somegarbagedomainyoudonthave.com](https://yourusername:yourpassword@carol.selfhost.de/nic/update?hostname=somegarbagedomainyoudonthave.com)
*   nochg 62.165.69.229 status:200 OK
*   [https://yourusername:yourpassword@carol.selfhost.de/nic/update?hostname=yourdomain.com&myip=garbage](https://yourusername:yourpassword@carol.selfhost.de/nic/update?hostname=yourdomain.com&myip=garbage)
*   abuse status: 200 OK
*   [https://yourusername:yourpassword@carol.selfhost.de/nic/update?hostname=yourdomain.com](https://yourusername:yourpassword@carol.selfhost.de/nic/update?hostname=yourdomain.com)
*   nochg 62.165.69.229 status: 200 OK

kr.,

Frepke

**Comment by qdm12** [comment]
Can you try the image with tag `:selfhost.de` and using this [readme](https://github.com/qdm12/ddns-updater/tree/selfhost.de)? Thanks!

**Comment by Frepke** [comment]
Tried it with the tag \`\`\`:selfhost.de\`\`\`

```
ddns-updater    | =========================================
ddns-updater    | =========================================
ddns-updater    | ========= DDNS Universal Updater ========
ddns-updater    | =========================================
ddns-updater    | === Made with ❤️  by github.com/qdm12 ====
ddns-updater    | =========================================
ddns-updater    | 
ddns-updater    | Running version selfhost.de built on 2020-12-09T00:54:02Z (commit 512d8f0)
ddns-updater    | 
ddns-updater    | 
ddns-updater    | 🔧  Need help? https://github.com/qdm12/ddns-updater/issues/new
ddns-updater    | 💻  Email? quentin.mcgaw@gmail.com
ddns-updater    | ☕  Slack? Join from the Slack button on Github
ddns-updater    | 💸  Help me? https://github.com/sponsors/qdm12
ddns-updater    | 2020-12-09T06:49:42.477Z      INFO    Found single setting to update record
ddns-updater    | panic: runtime error: invalid memory address or nil pointer dereference
ddns-updater    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9505cd]
ddns-updater    | 
ddns-updater    | goroutine 1 [running]:
ddns-updater    | main._main(0xc2b9a0, 0xc0000260a0, 0xa95b70, 0x0)
ddns-updater    |       github.com/qdm12/ddns-updater/main.go:114 +0xaed
ddns-updater    | main.main()
ddns-updater    |       github.com/qdm12/ddns-updater/main.go:32 +0x45
ddns-updater exited with code 2
```

For the readme: for "username" and "password" use the Dyn-DNS credentials

**Comment by qdm12** [comment]
> Tried it with the tag

Oupsi, that [single letter](https://github.com/qdm12/ddns-updater/pull/122/commits/cda46fc43703060418197628299aff464ac9c3e2)! Can you try repulling it?

> For the readme: for "username" and "password" use the Dyn-DNS credentials

Done thanks 👍

**Comment by Frepke** [comment]
> 
> 
> > Tried it with the tag
> 
> Oupsi, that [single letter](https://github.com/qdm12/ddns-updater/pull/122/commits/cda46fc43703060418197628299aff464ac9c3e2)! Can you try repulling it?
> 
> > For the readme: for "username" and "password" use the Dyn-DNS credentials
> 
> Done thanks 👍

Excellent 👍 
What a difference a "d" makes 😄 

kr.,
Frepke
