### ISSUE TITLE
Unable to start, error: `port "" is not a valid integer`

### ISSUE THREAD

**Issue by xaionaro** [qdm12/ddns-updater#131]
```
user@dx-ddns:~/go/bin$ ./updater 
=========================================
=========================================
========= DDNS Universal Updater ========
=========================================
=== Made with ❤️  by github.com/qdm12 ====
=========================================

Running version ? built on ? (commit ?)


🔧  Need help? https://github.com/qdm12/ddns-updater/issues/new
💻  Email? quentin.mcgaw@gmail.com
☕  Slack? Join from the Slack button on Github
💸  Help me? https://github.com/sponsors/qdm12
{"level":"ERROR","ts":"2020-12-13T13:38:30.425Z","msg":"port \"\" is not a valid integer"}
```

In `strace -f ./updater` I do not see any attempts to read any json file.

**Comment by qdm12** [comment]
Are you trying to run the binary out of the container? If so you need to set a few environment variables, you can have a look at the Dockerfile `ENV` instructions.

```sh
LISTENING_PORT=8000 updater
```

Should fix that one. If it complains more, you can adjust environment variables. I'll work on instructions to make it runnable out of a container today so let's leave the issue opened.

**Comment by xaionaro** [comment]
It helped. Thank you.

IMHO, the main problem here is unclear error reporting. It makes sense to mention `LISTENING_PORT` in the error message.

**Comment by qdm12** [comment]
Yep actually that's because of a dependency (qdm12/golibs) I got lazy at upgrading, will do it today 😅  Thanks for the feedback!

**Comment by qdm12** [comment]
Alright
