### ISSUE TITLE
Feature request: LuaDNS support

### ISSUE THREAD

**Issue by NotAUsername4Sure** [qdm12/ddns-updater#135]
1. What's the feature?
    Add support to update an LuaDNS IP address registration
2. Extra information?
    It uses Rest API so it may be hard. "https://www.luadns.com/api.html"

**Comment by qdm12** [comment]
Thanks! Oh on the contrary a REST API is easier for me (as long as it's not super convoluted like Azure's DNS 👀). I'll get to it during the Christmas break.

**Comment by qdm12** [comment]
A few initial questions (I'm coding it now):

1. Can you use a wildcard subdomain?
2. Can you use subdomains?

Thanks!

**Comment by NotAUsername4Sure** [comment]
> A few initial questions (I'm coding it now):
> 
> 1. Can you use a wildcard subdomain?
> 2. Can you use subdomains?
> 3. Can you use ipv6? Or is it limited to ipv4 addresses?
> 
> Thanks!

1. Yes
2. Yes
3. Yes

Also note that all these are included in the free package of the service. You are only limited on the number of the zones. It might help you develop faster. Thank you for taking the time to add this service, much appreciated !

**Comment by qdm12** [comment]
Thanks! Out of laziness, can you please try it with the image `qmcgaw/ddns-updater:luadns` and using [this readme](https://github.com/qdm12/ddns-updater/tree/luadns), as well as [that LuaDNS readme](https://github.com/qdm12/ddns-updater/blob/luadns/docs/luadns.md)?

If it gets complicated debugging it I'll sign up etc and test it out myself 👍

**Comment by NotAUsername4Sure** [comment]
I get the below error :
ERROR	email "examplename@outlook.com" is not valid

https://github.com/qdm12/ddns-updater/blob/luadns/internal/settings/luadns.go#L49

**Comment by qdm12** [comment]
Hmm strange. If you don't mind, as I use this check in other places too, can you please send me an email to [quentin.mcgaw@gmail.com](mailto:quentin.mcgaw@gmail.com) using that email address so I can run it through my regular expression check to see why it fails? Thanks!

**Comment by NotAUsername4Sure** [comment]
The email error is now fixed. 

Now i get the below when it tries to update the record :
> ERROR	cannot update record: Forbidden

I tried with different hosts. i.e. "*" "test" "". i get the same error. also tried with existing record and with non existing record.

Find below the logs :

host set to "*" without record on luadns

> ddns-updater    | 2020-12-29T13:43:07.039Z	INFO	Found single setting to update record
ddns-updater    | 2020-12-29T13:43:07.701Z	INFO	Reading history from database: domain example.com host *
ddns-updater    | 2020-12-29T13:43:07.701Z	INFO	http server: listening on 0.0.0.0:8000
ddns-updater    | 2020-12-29T13:43:07.702Z	INFO	healthcheck server: listening on 127.0.0.1:9999
ddns-updater    | 2020-12-29T13:43:07.702Z	INFO	backup: disabled
ddns-updater    | 2020-12-29T13:43:08.500Z	WARN	lookup any.example.com on 10.10.10.1:53: no such host
ddns-updater    | 2020-12-29T13:43:08.500Z	INFO	IPv4 address of any.example.com is <nil> and your IPv4 address is 29.41.77.18
ddns-updater    | 2020-12-29T13:43:08.500Z	INFO	Updating record [domain: example.com | host: * | provider: luadns | ip: ipv4] to use 29.41.77.18
ddns-updater    | 2020-12-29T13:43:09.429Z	ERROR	cannot update record: Forbidden

host set to "test" with record on luadns

> ddns-updater    | 2020-12-29T13:50:40.014Z	INFO	Found single setting to update record
ddns-updater    | 2020-12-29T13:50:40.685Z	INFO	Reading history from database: domain example.com host test
ddns-updater    | 2020-12-29T13:50:40.686Z	INFO	http server: listening on 0.0.0.0:8000
ddns-updater    | 2020-12-29T13:50:40.686Z	INFO	backup: disabled
ddns-updater    | 2020-12-29T13:50:40.686Z	INFO	healthcheck server: listening on 127.0.0.1:9999
ddns-updater    | 2020-12-29T13:50:41.567Z	INFO	IPv4 address of test.example.com is 21.55.93.44 and your IPv4 address is 29.41.77.18
ddns-updater    | 2020-12-29T13:50:41.567Z	INFO	Updating record [domain: example.com | host: test | provider: luadns | ip: ipv4] to use 29.41.77.18
ddns-updater    | 2020-12-29T13:50:42.531Z	ERROR	cannot update record: Forbidden

**Comment by qdm12** [comment]
Thanks for testing again! I pushed some commits to parse the error message and so on.

I decided (finally duh) to sign up on luadns and tested it with a domain (by the way, quite amazing it's free!) and it's working for me. Can you try pulling and try again?

If it fails again, are you sure you enabled API access in your settings as described [here](https://github.com/qdm12/ddns-updater/blob/luadns/docs/luadns.md#domain-setup)?

Thanks!

**Comment by NotAUsername4Sure** [comment]
It is working !! Thank you very much for integrating this into your project !!

**Comment by qdm12** [comment]
It's now merged in the main Docker image. Enjoy 🎉
