### ISSUE TITLE
I can rewrite frontend with vue

### ISSUE THREAD

**Issue by cnjack** [qdm12/ddns-updater#15]
Can I do with vue? [homepage](https://vuejs.org)

**Comment by cnjack** [comment]
ok,got it~ 👌

**Comment by qdm12** [comment]
Hi there,

I just added some Android notification support today (really felt the urge to add it!), I hope you did not start coding your frontend yet 😄 

Anyway, I will close the issue for now, feel free to comment here if you have any question for this Vue frontend or if I can help reworking the backend (as I'm not really familiar with Vue).
