### ISSUE TITLE
Feature request: Add support for *.yourdomain.tld on OVH

### ISSUE THREAD

**Issue by fredericrous** [qdm12/ddns-updater#153]
1. What's the feature?

Currently, the OVH provider updates the IP with OVH's dynhost service. This does not allow to update * records.

I am using Traefik, all the Softwares I use are under subdomains. I need to update A @ record + A * record

2. Extra information?

I created the following PR: https://github.com/qdm12/ddns-updater/pull/154

**Comment by qdm12** [comment]
Thanks! I invited you as a collaborator, that should make it easier for you to do PRs and all 😉
