### ISSUE TITLE
Help: i could not install on a RaspBerry Pi4 (4Gb model) running RaspBerry PI OS 64 bit

### ISSUE THREAD

**Issue by paolonervi** [qdm12/ddns-updater#166]
**TLDR**: The container is not running in as PI OS 64 bit RaspBerry PI4.

1. Is this urgent: No
2. DNS provider(s) you use: NOIP.COM
3. Program version: 

    

    `Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)`

4. What are you using to run the container: docker run 
5. Extra information (optional): i could not use docker-compose. I get an error about the version (3.7).

Logs:

```log

```

Configuration file (**remove your credentials!**):

```json

```

Host OS:  PI OS 64 bit

**Comment by qdm12** [comment]
Try pulling latest? The version you're using is quite old. Also you can use an older version of docker-compose by changing its version at the top or just upgrade your docker-compose version.

**Comment by paolonervi** [comment]
Hi! thank you for the time you dedicate in replying to me.
I've used this command:
`docker run -d -p 8000:8000/tcp -v "$(pwd)"/data:/updater/data qmcgaw/ddns-updater:latest`
So i think i'm using the latest version.

I've run: 
`sudo apt-get upgrade docker-compose`

and the result of the command _docker-compose version_ is the following:

```
docker-compose version 1.21.0, build unknown
docker-py version: 3.4.1
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

I try also to run the container in interactive mode and here may be is the problem..:

```
pi@pi-worker-01:~/data $ docker run --name ddns  -p 8000:8000/tcp -v "$(pwd)"/data:/updater/data qmcgaw/ddns-updater:latest
=========================================
=========================================
========= DDNS Universal Updater ========
=========================================
=== Made with ❤️  by github.com/qdm12 ====
=========================================

Running version latest built on 2021-01-30T20:01:15Z (commit 78c86b0)


🔧  Need help? https://github.com/qdm12/ddns-updater/issues/new
💻  Email? quentin.mcgaw@gmail.com
☕  Slack? Join from the Slack button on Github
💸  Help me? https://github.com/sponsors/qdm12
2021-02-07T14:43:40.451Z        ERROR   cannot write to file "/updater/data/updates.json": open /updater/data/updates.json: permission denied_

```
It seems a permission problem, but I'm new at Linux and I don't know how to solve this...
If you have any suggestions let me know.

Thank you very much for the time you dedicate in helping me.

Greetings from Italy.

Paolo.

**Comment by fredericrous** [comment]
try something like:

`docker run --user $(id -u):$(id -g) -d -p 8000:8000/tcp -v "$(pwd)"/data:/updater/data qmcgaw/ddns-updater:latest`

you need to set a user for the container that has the same uid than the one that owns your data folder. This is documented under the section setup of https://hub.docker.com/r/qmcgaw/ddns-updater/

**Comment by paolonervi** [comment]
Tks!
I'll try asap.
Paolo.

**Comment by paolonervi** [comment]
As far as you know what is ther correct syntax for the variables in the config.json file for the NOIP.COM site?
If you follow the [link](https://hub.docker.com/r/qmcgaw/docs/noip.md) indicate you'll get an error...
Tks.
Paolo.

**Comment by paolonervi** [comment]
...but DynDNS is'nt supported?

`2021-02-07T15:32:25.809Z        ERROR   provider "DynDNS" is not supported`

Thank for your help...
Paolo.

**Comment by fredericrous** [comment]
The correct id for DynDNS is "dyn". The documentation is here https://github.com/qdm12/ddns-updater/blob/master/docs/dyndns.md

**Comment by fredericrous** [comment]
Happy to know you were able to make ddns-updater work Paolonervi. Let's close this issue once https://github.com/qdm12/ddns-updater/pull/167 is reviewed and merged

**Comment by qdm12** [comment]
Thanks @fredericrous for helping out!

@paolonervi also note that if you run on your host as root (`id -u` being `0`), you should ideally not run the container with `--user $(id -u):$(id -g)` and just change the ownership and permission of the directory & files as described [here](https://github.com/qdm12/ddns-updater#setup).
