### ISSUE TITLE
Feature request: custom provider

### ISSUE THREAD

**Issue by fredericrous** [qdm12/ddns-updater#168]
1. What's the feature?

Give users the ability to configure a custom provider. Looking at the current list of providers, I see a lot of providers are essentially calling one URL with a get request. We could give users the ability to define a url

```
{
    "settings": [
        {
            "provider": "custom",
            "domain": "example.com",
            "url": "https://someddns.service/update?domain=mondomain.fr&monToken=token&monIP",
            "displayName": "SomeDDNS"
        }
    ]
}
```

2. Extra information?

We could go further by letting the user define a return code or to let him define HTTP headers, however in most cases the response seems to be 200 and no extra header is needed

The cons I see of implementing this is that we won't know which provider users are using (without some kind of anonymous analytics on which user could opt out)
The pros: less providers to implement, more providers supported by just documenting how to set them up

**Comment by fredericrous** [comment]
That's just a suggestion. As I'm using wildcard records with gandi and ovh I don't use this kind of paradigm. But I think that it could reduce the amount of code to maintain. And writing doc is sure less fun than coding but way faster ^^

**Comment by qdm12** [comment]
A few of them use the dyndns protocol with tiny variations. We could tackle that 👍

But otherwise, it's highly variable between each provider and not just a GET request.

**Comment by Jano69** [comment]
is there any progress to be able to use a custom url?

**Comment by qdm12** [comment]
Not yet, do you have a url in mind? I can add it today if you want.

**Comment by Jano69** [comment]
ok no problem:
Provider 1: (domaindiscount24.com / dd24.net)
--------------
Mit dem Dynamic DNS Feature können Sie dynamische IP-Adressen von allen Domains, die in ihrem Namen registriert sind, automatisch updaten. Die meisten Router oder Modems unterstützen automatische DNS Updates für den Fall, dass die lokale IP Adresse wechselt. Durch die Konfiguration der DynamicDNS URL kann dieser Prozess mit jedem registrierten Domain Namen automatisiert werden .

Um den DynamicDNS Host zu aktualisieren, müssen Sie die folgende HTTP APIs aufrufen:

https://dynamicdns.key-systems.net/update.php?hostname=hostname&password=password&ip=auto
https://dynamicdns.key-systems.net/update.php?hostname=hostname&password=password&ip=213.4.7.1&mx=213.4.7.1 

Provider 2: ( spdyn.de - Securepoint
Dynamic-DNS-Service)

https://update.spdyn.de/nic/update?hostname=<host>&myip=<ipaddr>&user=<username or domain when use token>&pass=<pass or token>

very thx

**Comment by Jano69** [comment]
btw. Securepoint Dynamic-DNS-Service:

if the token is activated, the host name must be used for the username!

**Comment by Jano69** [comment]
> 
> 
> Not yet, do you have a url in mind? I can add it today if you want.

you have any news for me ?

**Comment by qdm12** [comment]
I'll to do it this evening. I haven't forgotten, sorry for the delay 😉 I was busy working on #158 and #178 (for a newer UI).

**Comment by qdm12** [comment]
I need a bit of information for domaindiscount24. Can you try the following urls using your browser replacing:

- `domain.com` with your hostname
- `password` with your actual password

1. https://dynamicdns.key-systems.net/update.php?hostname=domain.com&password=password&ip=auto
2. https://dynamicdns.key-systems.net/update.php?hostname=domain.com&password=password&ip=127.0.0.1
3. https://dynamicdns.key-systems.net/update.php?hostname=domain.com&password=password&ip=::1
4. https://dynamicdns.key-systems.net/update.php?hostname=domain.com&password=password&ip=blabla
5. https://dynamicdns.key-systems.net/update.php?hostname=domain.com&password=password

I'm working on spdyn.de but it looks like they have a quite detailed documentation so I should be fine.

**Comment by qdm12** [comment]
Also can you try the image `qmcgaw/ddns-updater:spdyn` with documentation [here](https://github.com/qdm12/ddns-updater/tree/spdyn) see if it works for you? Thanks!

**Comment by qdm12** [comment]
@Jano69 Let's continue the discussion on #182 and #183 for each provider, as it's highly irrelevant here. I'll delete the previous messages we had to keep this issue tidy.

**Comment by Jano69** [comment]
Hi qdm12, I'm looking for a docker file with the Telerising Zattoo API and integrated OpenVPN to bypass geoblocking. Would you like to? The original Dockerfile is available at https://github.com/DeBaschdi/docker.new-telerising-api/issues/4

Greetings to CANADA and Happy Easter!

**Comment by qdm12** [comment]
Hi Jano, thanks for the greets, happy easter too🥚

Not that I want to ruin the party, but this seems very far away from this repo.

Feel free to Slack me (ideally not on the channel, but by private message to Quentin):

[![Join Slack channel](https://img.shields.io/badge/slack-@qdm12-yellow.svg?logo=slack)](https://join.slack.com/t/qdm12/shared_invite/enQtODMwMDQyMTAxMjY1LTU1YjE1MTVhNTBmNTViNzJiZmQwZWRmMDhhZjEyNjVhZGM4YmIxOTMxOTYzN2U0N2U2YjQ2MDk3YmYxN2NiNTc)

About this as I have no clue what that telerising api is or how it would be relevant to this repo or other of my repositories.

I'll delete both this message and your message once you reach me on Slack to keep this issue tidy. Please don't use this issue to communicate about other things, that's not the purpose of it.

**Comment by Jano69** [comment]
thx, you can delete the message... the invite is not working....

**Comment by qdm12** [comment]
Oops sorry about that try [This one](Join my Slack workspace! https://join.slack.com/t/qdm12/shared_invite/zt-bo6ztdzb-Yv7pNwuO5LvSUW2IRpAMMQ)

**Comment by qdm12** [comment]
Done in 0c561d437816022383a89076850e10642ca142a9

Documentation is at https://github.com/qdm12/ddns-updater/blob/master/docs/custom.md

It's sort of simple for now, but could be extended to some extent until implementing the provider specific code in Go would be simpler.
