### ISSUE TITLE
Bug: ...Documentation for duckdns is incorrectly the same as dreamcast.

### ISSUE THREAD

**Issue by kclute** [qdm12/ddns-updater#171]
**TLDR**: documentation for duckdns is incorrect, should be "provider": "duckdns", "host": "hostname (without.duckdns.org)", "token": "....",   

1. Is this urgent: No
2. DNS provider(s) you use: DuckDNS, FreeDNS
3. Program version:

    

    `Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)`

4. What are you using to run the container: docker-compose
5. Extra information (optional)

Logs:

```log

```

Configuration file (**remove your credentials!**):

```json

```

Host OS:

**Comment by qdm12** [comment]
Thanks!! And sorry for the trouble it caused you, indeed that was plain wrong due to my lacking copy pasta skills!
