### ISSUE TITLE
Feature request: ... Add FreeDNS

### ISSUE THREAD

**Issue by kclute** [qdm12/ddns-updater#172]
1. What's the feature?  Possibly add the DDNS FreeDNS

2. Extra information?  https://freedns.afraid.org

**Comment by qdm12** [comment]
In their example ` curl https://sync.afraid.org/u/CyTXMbtq5cPnLjEg5vKHTPDE/`, `CyTXMbtq5cPnLjEg5vKHTPDE` is your token right? Or should I call it username? Thanks!

**Comment by qdm12** [comment]
Maybe you can test the image `qmcgaw/ddns-updater:freedns` with this [documentation](https://github.com/qdm12/ddns-updater/tree/freedns) to save me some time 😉 I called that `CyTXMbtq5cPnLjEg5vKHTPDE` as `id` but let me know if you think it should be something else.

**Comment by kclute** [comment]
sorry for the repeat if you already saw my email..  

Tried to use :freedns and I get the following errror:

ddns-updater    | standard_init_linux.go:219: exec user process caused: exec format error


I am probably setting the config.json up incorrectly since I am not sure what you want for all the fields.  I tried several different values but always got the same error.  And as expected if I use the :latest version it complains about not having "freedns" as a provider.

I use the recommended method of Randomized Update Token and the only required field is the token/id, filled host and domain with my info for identification purpose only.  i.e.   If my ddns was my-host-name.any-domain.com


config.json file
{
  "settings": [
        {
           "provider": "freedns",
           "domain": "any-domain.com",
           "host": "my-host-name",
           "id": "CyTXMbtq5cPnLjEg5vKHTPDE"
        }
    ]
}

command
http://sync.afraid.org/u/CyTXMbtq5cPnLjEg5vKHTPDE/    # token is fake :) 

listed supported update styles, I have only used first so unable to help on others
**Randomized UpdateToken**           | Default option, simple, secure, my personal favorite.
**Username and Password, inline**  | Username and password as URI arguments, rather then the HTTP authentication
**Username and Password**             | Uses HTTP authentication, if you'd rather use a username/password,  
                                                       some routers like to implement this method or can be most easily adapted to this method
/**nic/update**                                   | Uses HTTP authentication, I've seen update attempts like these hitting the server.

**Comment by qdm12** [comment]
> I am probably setting the config.json up incorrectly

Nope you're not! It's just docker images built from branches are only built for amd64 CPUs, let me fix that to include all architectures (ARM etc.). It's building now (wait for the green tick just above this comment).

> I use the recommended method of Randomized Update Token

I will change the `id` field to `token` then. The program needs the `host` and `domain` to DNS resolve them periodically and also to display them in the UI. And yes let's stick to the `Randomized UpdateToken` for now, adding more options doesn't really add any benefit.

**Comment by kclute** [comment]
Sorry for not including the OS in original message containing error.  I am using arm64, raspberry OS 64bit.

**Comment by qdm12** [comment]
It's rebuilt you can try pulling it again and it will pull for your arch. Also use token instead of id.

**Comment by kclute** [comment]
I receive this error.
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Pulling ddns-updater (qmcgaw/ddns-updater:freedns)...
freedns: Pulling from qmcgaw/ddns-updater
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by qdm12** [comment]
Ah! I added armv6 and armv7, but forgot about arm64! It should now be available to pull, sorry about that 😉 (if it's not wait for [the build](https://github.com/qdm12/ddns-updater/actions/runs/585106855))

**Comment by kclute** [comment]
Looks like this build worked.  Thank you for all your work.

**Comment by qdm12** [comment]
So it's working fine? Can I merge that in the main code and latest image? Thanks!

**Comment by kclute** [comment]
Far as I can tell it is working with no errors in the log. I changed my freedns ip to my phone's ip so it would have to reset it. It did. So in my limited test it worked, so yeah go ahead and merge it. Not sure if you are interested but you can add your app on their site. https://freedns.afraid.org/scripts/freedns.clients.php

**Comment by qdm12** [comment]
Cool 🎉  I merged it into the base `qmcgaw/ddns-updater` image.
