### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by bickers117** [qdm12/ddns-updater#18]
I have been continually getting the following error since the most recent image update a few days ago. Seems to be triggered by the addition of a Gotify notification trigger for a new IP address assignment.

>panic: runtime error: index out of range [0] with length 0
>goroutine 51 [running]:
>ddns-updater/pkg/update.update(0xc0005994d0, 0xc0005960c0, 0xc0006c4180, 0xc000373780)
>	/tmp/gobuild/pkg/update/update.go:148 +0x12a0
>created by ddns-updater/pkg/update.periodicServer
>	/tmp/gobuild/pkg/update/trigger.go:76 +0x1b8

**Comment by qdm12** [comment]
Thanks for pointing this out! 

I fixed it, ah I really need to write more unit tests sorry about that!
