### ISSUE TITLE
Feature request: Spdyn support

### ISSUE THREAD

**Issue by qdm12** [qdm12/ddns-updater#182]
See #179  and #168 

@Jano69 Can you try the image `qmcgaw/ddns-updater:spdyn` with documentation [here](https://github.com/qdm12/ddns-updater/tree/spdyn) see if it works for you? Thanks!

**Comment by Jano69** [comment]
it works fine !


test.spdns.eu | @ | Spdyn DNS | ipv4 | Up to date (no IP change for 5m), 16s ago | 89.12.247.127 | N/A
