### ISSUE TITLE
Feature request: Support dd24.net

### ISSUE THREAD

**Issue by qdm12** [qdm12/ddns-updater#183]
See #168 

@Jano69 I need a bit of information for domaindiscount24. Can you try the following urls using your browser replacing:

- `domain.com` with your hostname
- `password` with your actual password

1. https://dynamicdns.key-systems.net/update.php?hostname=domain.com&password=password&ip=auto
2. https://dynamicdns.key-systems.net/update.php?hostname=domain.com&password=password&ip=127.0.0.1
3. https://dynamicdns.key-systems.net/update.php?hostname=domain.com&password=password&ip=::1
4. https://dynamicdns.key-systems.net/update.php?hostname=domain.com&password=password&ip=blabla
5. https://dynamicdns.key-systems.net/update.php?hostname=domain.com&password=password

**Comment by Jano69** [comment]
at domaindiscount you can order your own domain and activate it as dyndns. All name server configurations can be made. Similar to selfhost.de. domain.com is an individual domain that you have ordered. The password can also be set freely. A username is not necessary for this service. Domain name and password is just important.

**Comment by qdm12** [comment]
I know, I just need you to try the following URLs above to see what responses you get so that I can code all the edge cases in the program. As most providers don't totally respect the dyndns spec so we need to check their response manually.

**Comment by qdm12** [comment]
Did you have some time to check those 5 urls? I would like to merge this soon ideally. Thanks!

**Comment by qdm12** [comment]
Hey @Jano69 does it work for you? Thanks!

**Comment by qdm12** [comment]
Merged in ee66170a8747335210f47698f4f6f4a4be1fdc9e
