### ISSUE TITLE
Wildcard Entries for Dreamhost

### ISSUE THREAD

**Issue by danmandle** [qdm12/ddns-updater#19]
When trying to update `*.exampledomain.com`, I the following error message:

> {"level":"WARN","ts":"2019-10-29T00:32:30.973Z","msg":"invalid domain name format for settings {\"domain\":\"*.exampledomain.com\",\"host\":\"@\",\"provider\":\"dreamhost\"}","node_id":0}`

Config:
> {
      "provider": "dreamhost",
      "domain": "*.exampledomain.com",
      "ip_method": "duckduckgo",
      "key": "XXXXXXX"
    }

Current workaround: CNAME `*.exampledomain.com` > `exampledomain.com`

**Comment by qdm12** [comment]
It should have the domain `exampledomain.com` and host `*`. Also I'm not sure it works with CNAME, it's meant to work with A records only as I recall. Let me know if it works, thanks!

**Comment by danmandle** [comment]
Thanks for the lighting fast response! It was set to an A record when testing, CNAME as workaround. Updating to `host: *` fixed the error message. Not sure if it actually updated the record, but that may have been due to rapid DNS changes. Will verify later.

**Comment by danmandle** [comment]
I may have gotten my hopes up too soon. The error has gone away, but the value isn't changing. 
Screen shot from Dreamhost:
![screenshot](https://i.imgur.com/dANZaQV.png)

**Comment by qdm12** [comment]
Is it working now? You might need to give it some time to update.
