### ISSUE TITLE
Bug: IP version indicator not rendered

### ISSUE THREAD

**Issue by hugalafutro** [qdm12/ddns-updater#190]
**TLDR**: *IP version column displays square (unrenderable utf8 character or w/e it's called) after latest update. Using Vivaldi x64 browser*

1. Is this urgent: No
2. DNS provider(s) you use: noip
3. Program version:

    

    ` Running version latest built on 2021-03-23T02:18:19Z (commit 869cf52)`

4. What are you using to run the container: docker-compose
5. Extra information (optional)

![Screenshot 2021-03-23 223443](https://user-images.githubusercontent.com/30209689/112227736-05463600-8c28-11eb-97cc-e9fd73986f9b.png)

Host OS: raspbian 32bit (Pi3b+)
only using ip4

**Comment by qdm12** [comment]
Thanks for creating the issue, I wouldn't had noticed 😉 It should be fixed now 👍
