### ISSUE TITLE
`ionos.de`

### ISSUE THREAD

**Issue by vaughngx4** [qdm12/ddns-updater#194]
Hi! Thanks for the awesome docker image. I have not yet tried but could you possibly add native support for IONOS DDNS? My domain is with them and they use domain-connect-dyndns.

Honestly as a dev I should have probably looked at the code first but I'm so busy working on other projects I thought send a feature request.

Much love!

https://developer.hosting.ionos.de/docs/dns

**Comment by qdm12** [comment]
Hi there, happy to implement it. 

However, I'm struggling to find what HTTP routes they have to trigger the update, would you perhaps have a clue for me?

Thanks!

**Comment by vaughngx4** [comment]
Not 100% However the source for the update client they use is on Github:

https://github.com/Domain-Connect/DomainConnectDDNS-Python

Thanks!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by cycl0ne** [comment]
Here is the Developer API from Ionos:
https://developer.hosting.ionos.com/docs/dns

**Comment by qdm12** [comment]
@gordonfreemanc17 @SHemeier (from duplicate issue)

**Comment by qdm12** [comment]
It should be done in commit ff5767aa382b34964d5963d49a9f72a857b3a87d (latest image, and future release v2.6.0.
If it doesn't work, please open a new issue, thanks!
