### ISSUE TITLE
Help: ...

### ISSUE THREAD

**Issue by wwei76922** [qdm12/ddns-updater#199]
**TLDR**: *Describe your issue in a one liner here*

1. Is this urgent: Yes/No
2. DNS provider(s) you use: Answer here
3. Program version:

    

    `Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)`

4. What are you using to run the container: docker-compose
5. Extra information (optional)

Logs:

```log

```

Configuration file (**remove your credentials!**):

```json

```

Host OS:

**Comment by qdm12** [comment]
There is no information 🤔
