### ISSUE TITLE
Feature request: ...「 https://dynv6.github.io/api-spec/#operation/addRecord 17 」
----------------「 https://github.com/qdm12/ddns-updater/issues/201 」
----------------



### ISSUE THREAD

**Issue by wwei76922** [qdm12/ddns-updater#201]
1. What's the feature?

2. Extra information?

**Comment by wwei76922** [comment]
https://github.com/qdm12/ddns-updater/issues/201

**Comment by wwei76922** [comment]
> https://github.com/qdm12/ddns-updater/issues/201

「 https://github.com/qdm12/ddns-updater/issues/201#issue-887979866 」
----------------

**Comment by qdm12** [comment]
Can you stop posting non sense issues please?
