### ISSUE TITLE
Feature request: Support multiple notification services

### ISSUE THREAD

**Issue by fredericrous** [qdm12/ddns-updater#205]
1. What's the feature?
Get notified on discord

2. Extra information?

pretty much like godns does https://github.com/TimothyYe/godns#discord
gotify notifications are great. But I tend to let the app closed. I, therefore, use it as audit logs instead of a notifier

**Comment by qdm12** [comment]
Let's use https://github.com/crazy-max/diun/ as suggested by @bozzfozz [here](https://github.com/qdm12/gluetun/issues/131#issuecomment-803627655) so multiple notification services are supported 👍

**Comment by qdm12** [comment]
Actually diun is a bad choice, we'll use https://containrrr.dev/shoutrrr/ instead

**Comment by qdm12** [comment]
Done in 4133dbfdc7400eac268f4a08680cd563ed3ffc70 see the `SHOUTRRR_ADDRESSES` environment variable in the readme table.

It will be included in v2.4.0.
