### ISSUE TITLE
gluetun published in place of ddns updater

### ISSUE THREAD

**Issue by fredericrous** [qdm12/ddns-updater#232]
this is what appears when I start qmcgaw/ddns-updater

![image](https://user-images.githubusercontent.com/702227/129489770-ef8212e8-1158-448a-b07c-dfe94b7f3be5.png)

**Comment by qdm12** [comment]
Oh oh even on `:latest`? I remembered there was a CI bug back then. I'll check tomorrow.

**Comment by fredericrous** [comment]
yup, latest. ![image](https://user-images.githubusercontent.com/702227/129534189-94ad0ea8-a364-4933-af14-4fe24b63e397.png)

**Comment by qdm12** [comment]
Ah oof, it was just a bad string 😉  the program was still the right one!

**Comment by fredericrous** [comment]
oh ok, sorry I scared you (and me xD)
