### ISSUE TITLE
Provider: all-inkl.com

### ISSUE THREAD

**Issue by JD101010** [qdm12/ddns-updater#245]
Update URL: dyndns.kasserver.com/

URL with IP: dyndns.kasserver.com/?myip=<ipaddr>

URL with IPv4 & v6: dyndns.kasserver.com/?myip=<ipaddr>&myip6=<ip6addr>

**Comment by marc2016** [comment]
Hi, I need this provider too. Are you started with the implementation?
If not, I would try to add this provider and try to create an PR in the next few days?

**Comment by qdm12** [comment]
Hi @marc2016 I haven't started the implementation.

There is a rather big backlog of providers to add, and I'm lacking time and need to fix some existing bugs/refactor the code before adding more (and also I have other repos and I'm traveling this week 😄). So please do a PR if you want! You can check existing merged PRs for example on how to do it, usually a single Go file and a few tiny modifications in other go files are only what's needed.

**Comment by marc2016** [comment]
Hi @qdm12!

I created a PR :-) 
Thank you for this great project!

**Comment by qdm12** [comment]
Done in 584597d5cb8c5ce8edfc9f5f15a387e1932ab174

Thanks everyone for your work/patience!
