### ISSUE TITLE
netcup.de

### ISSUE THREAD

**Issue by proohit** [qdm12/ddns-updater#282]
Their API is documented [on their technical documentation page](https://ccp.netcup.net/run/webservice/servers/endpoint.php). They have [more general docs here](https://www.netcup-wiki.de/wiki/DNS_API), but unfortunately they are only in german.

**Comment by qdm12** [comment]
If anyone can try image tag `:netcup` with documentation at https://github.com/Azorimor/ddns-updater/blob/provider-netcup/docs/netcup.md and let me know if it works or not on #361 that would help 😉

**Comment by qdm12** [comment]
@salapate @Assaro

**Comment by Assaro** [comment]
Thank you. Will try it ASAP and give you feedback

**Comment by qdm12** [comment]
Done in 09eb9e706dbca58fd10a3c71f75b58e6ca3e2aac

This is available in the latest image and future release v2.6.0
