### ISSUE TITLE
`freemyip.com`

### ISSUE THREAD

**Issue by MilorES** [qdm12/ddns-updater#288]
https://freemyip.com/help

**Comment by psycho-dad** [comment]
me too

**Comment by Node815** [comment]
Please add this!

**Comment by ahmaddxb** [comment]
i need it too

**Comment by bentemple** [comment]
Can look into adding this. FWIW, this _should_ be functional with the [custom](https://github.com/qdm12/ddns-updater/blob/master/docs/custom.md) type provider. I believe the config would look like this for an ipv4 address, where `YOUR_DOMAIN.freemyip.com` is your domain and `YOUR_TOKEN` is your `freemyip.com` is your token.
```
{
  "settings": [
    {
      "provider": "custom",
      "domain": "YOUR_DOMAIN.freemyip.com",
      "url": "https://freemyip.com/update?token=YOUR_TOKEN&domain=YOUR_DOMAIN.freemyip.com"
      "ipv4key": "myip",
      "ipv6key": "ipv6",
      "success_regex": "OK",
      "ip_version": "ipv4"
    }
  ]
}
```

**Comment by Node815** [comment]
One small correction to this, I had to add a comma after the URL to make it work:
```{
  "settings": [
    {
      "provider": "custom",
      "domain": "YOUR_DOMAIN.freemyip.com",
      "url": "https://freemyip.com/update?token=YOUR_TOKEN&domain=YOUR_DOMAIN.freemyip.com",
      "ipv4key": "myip",
      "ipv6key": "ipv6",
      "success_regex": "OK",
      "ip_version": "ipv4"
    }
  ]
}```

**Comment by MilorES** [comment]
It works perfectly

**Comment by bentemple** [comment]
> One small correction to this, I had to add a comma after the URL to make it work:
> 
> ```
>   "settings": [
>     {
>       "provider": "custom",
>       "domain": "YOUR_DOMAIN.freemyip.com",
>       "url": "https://freemyip.com/update?token=YOUR_TOKEN&domain=YOUR_DOMAIN.freemyip.com",
>       "ipv4key": "myip",
>       "ipv6key": "ipv6",
>       "success_regex": "OK",
>       "ip_version": "ipv4"
>     }
>   ]
> }
> 
> One more edit to add, for those who use Freemyip like I do.  
> 
> You can simply go to your bookmarked page (if you have done this like I have), then you can copy the link they give you such as https://freemyip.com/help?domain=YOURDOMAIN.freemyip.com&token=YOURTOKEN  it will return a page showing the URL you can copy and paste into the URL string above.  
> ```

thanks for verifying and the correction. Copy paste error got me :)
