### ISSUE TITLE
[BUG] dnspod now need ID in config

### ISSUE THREAD

**Issue by ZhaoUncle** [qdm12/ddns-updater#289]
![image](https://user-images.githubusercontent.com/31182637/148362728-685bfe1f-6890-4247-92c5-53c7c376466f.png)

**Comment by ZhaoUncle** [comment]
dnspod config token is "id,token"

**Comment by qdm12** [comment]
Hey sorry for the delay, is it working now?

**Comment by ZhaoUncle** [comment]
yes, test is ok

**Comment by xiaokuihua2333** [comment]
hello , can your tell me how to write dnspod config

**Comment by qdm12** [comment]
@xiaokuihua2333 See the readme and https://github.com/qdm12/ddns-updater/blob/master/docs/dnspod.md
