### ISSUE TITLE
Bug: ERROR invalid public IP HTTP provider: ddnss

### ISSUE THREAD

**Issue by maboxx** [qdm12/ddns-updater#298]
1. Is this urgent: Yes/No
    No
2. DNS provider(s) you use: 
    DDNSS
3. Program version:
    `Running version latest built on 2022-01-21T13:37:49Z (commit f5b76f2)`
4. What are you using to run the container: docker-compose with following option as here descriptes https://github.com/qdm12/ddns-updater#Public-IP
    PUBLICIP_HTTP_PROVIDERS=ddnss,opendns,ifconfig

Logs:

```log
Running version latest built on 2022-01-21T13:37:49Z (commit f5b76f2)

🔧 Need help? https://github.com/qdm12/ddns-updater/discussions/new

🐛 Bug? https://github.com/qdm12/ddns-updater/issues/new

✨ New feature? https://github.com/qdm12/ddns-updater/issues/new

☕ Discussion? https://github.com/qdm12/ddns-updater/discussions/new

💻 Email? quentin.mcgaw@gmail.com

💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12

2022/01/25 16:32:43 ERROR invalid public IP HTTP provider: ddnss
```

Host OS: Docker

**Comment by qdm12** [comment]
Please recheck the readme, `PUBLICIP_HTTP_PROVIDERS` cannot be `ddnss`. This is just providers to echo back your public IP address by HTTP, not the DNS provider you want to communicate with.
