### ISSUE TITLE
Bug: IPv6 Strato Update is not working anymore

### ISSUE THREAD

**Issue by HeikoB95** [qdm12/ddns-updater#302]
IPv6 Strato Update is not working anymore

1. Is this urgent: Yes
2. DNS provider(s) you use: strato
3. Program version: 

    

    `Running version latest built on 2022-01-21T13:37:49Z (commit f5b76f2)`

4. What are you using to run the container: docker-compose
5. Extra information (optional)

Logs:

```log
2022/01/31 11:18:09 WARN obtaining ipv6 address: try 1 of 3: dial udp6 [2606:4700:4700::1001]:53: connect: network is unreachable
2022/01/31 11:18:09 WARN obtaining ipv6 address: try 2 of 3: Get "http://ip1.dynupdate6.no-ip.com": dial tcp [2a07:dc00:1330:2::204]:80: connect: network is unreachable
2022/01/31 11:18:09 WARN obtaining ipv6 address: try 3 of 3: dial udp6 [2001:4860:4802:32::a]:53: connect: network is unreachable
2022/01/31 11:18:09 ERROR dial udp6 [2001:4860:4802:32::a]:53: connect: network is unreachable
```

Configuration file (**remove your credentials!**):

```json
{
  "settings" : [
    {
      "provider": "strato",
      "domain": "XYZ.de",
      "host": "@,ab,cd",
      "password": "XXXXXXXXXX",
      "ip_version": "ipv4",
      "provider_ip": true
    },
    {
      "provider": "strato",
      "domain": "XYZ.de",
      "host": "@,ab,cd",
      "password": "XXXXXXXXXX",
      "ip_version": "ipv6",
      "provider_ip": true
      }
  ]
}
```

Host OS:
Synology DSM7.0.1

**Comment by qdm12** [comment]
Hey there, sorry for the mega-delay... What was the problem? Was the network down :sweat_smile: ?

**Comment by NightFurySL2001** [comment]
I just encountered this issue and found out it's related to IPv6 support in Docker containers, which are not enabled by default. Follow the setup in https://docs.docker.com/config/daemon/ipv6/ to allow experimental IPv6 support which will resolve this issue.
