### ISSUE TITLE
Maintenance: use `net/netip` when upgrade to Go 1.18 is possible

### ISSUE THREAD

**Issue by qdm12** [qdm12/ddns-updater#314]
1. What's the feature?

Use https://pkg.go.dev/net/netip which is more robust and better than the current `net.IP` addresses

3. Extra information?

This needs Go 1.18 which doesn't work with golangci-lint currently, so we'll have to wait.

**Comment by rgm3** [comment]
golangci-lint supports go 1.18 since v1.45.0, although some linters that do not support go 1.18 may be disabled.  For details, see https://github.com/golangci/golangci-lint/issues/2649.

**Comment by qdm12** [comment]
Yes that's rather unfortunate a bunch of linters are not compatible. Thanks for mentioning this.
Since this issue is not really urgent, I'lll probably delay the upgrade to Go 1.18 until all golangci-lint linters are working again.

**Comment by qdm12** [comment]
Done in 9a4a268926c73f360578cf4a2a9d75a156541250
