### ISSUE TITLE
DuckDNS ERROR: Mismatching IP address received

### ISSUE THREAD

**Issue by whoshoe** [qdm12/ddns-updater#320]
**TLDR**: *Update to DcukDNS failed*

Update query didn't generate any errors but DNS record didn't get updated. Error in the log file: _ERROR mismatching IP address received: xx.xx.xx.xx_

1. Is this urgent: Yes
2. DNS provider(s) you use: DuckDNS
3. Program version:

    

    `Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)`

4. What are you using to run the container: docker command from unRaid
5. Extra information (optional)

Logs:

```log
2022/03/19 21:37:13 INFO IPv4 address of xxxx.duckdns.org is 2x.xx.xx.xx and your IPv4 address is 1x.xx.xx.xx
2022/03/19 21:37:13 INFO Updating record [domain: duckdns.org | host: xxxx| provider: duckdns | ip: ipv4] to use 1x.xx.xx.xx
2022/03/19 21:37:14 ERROR mismatching IP address received: 2x.xx.xx.xx
```

Configuration file (**remove your credentials!**):

```json
{
  "settings": [
    {
      "provider": "duckdns",
      "domain": "duckdns.org",
      "host": "xxxx",
      "token": "a632273f-xxxx-xxxx-98ef-3ff547207f7e",
      "ip_version": "ipv4",
      "provider_ip": true
    }
  ]
}
```

Host OS:
UnRAID (Debian based)

**Comment by qdm12** [comment]
In your browser what do you get when accessing:

`https://www.duckdns.org/update?verbose=true&domains=xxxx&token=a632273f-xxxx-xxxx-98ef-3ff547207f7e&ip=1x.xx.xx.xx`

(replace values as well)

Do you get the IP you sent `1x....` or the older one `2x....`??

**Comment by whoshoe** [comment]
> https://www.duckdns.org/update?verbose=true&domains=xxxx&token=a632273f-xxxx-xxxx-98ef-3ff547207f7e&ip=1x.xx.xx.xx

Here's the response I got directly from the browser (I am using Chrome):
```
OK
1x.xx.xx.xx

UPDATED
```

**Comment by qdm12** [comment]
I just realise you were running `Running version latest built on 2020-03-13T01:30:06Z` and this issue is from march 2022... maybe try `docker pull qmcgaw/ddns-updater` and restart the container to see if it works?

**Comment by qdm12** [comment]
This should be resolved in the latest image now (and also perhaps in previous release v2.5.0)
