### ISSUE TITLE
Bug: dnspod ipv6 update failed 

### ISSUE THREAD

**Issue by jibwf** [qdm12/ddns-updater#327]
dnspod to update both ipv4 and ipv6. IPv6 update failed due to "ERROR not found"

1. Is this urgent: No
2. DNS provider(s) you use: dnspod
3. Program version:
Running version latest built on 2022-03-15T14:38:50Z (commit 584597d)

4. What are you using to run the container: unraid

5. Extra information (optional)

Logs:

```
2022/04/07 11:56:42 INFO reading JSON config from file /updater/data/config.json
2022/04/07 11:56:42 INFO Found 2 settings to update records
2022/04/07 11:56:42 INFO Reading history from database: domain dclife.fun host nas
2022/04/07 11:56:42 INFO Reading history from database: domain dclife.fun host nas
2022/04/07 11:56:42 INFO healthcheck server: listening on 127.0.0.1:9999
2022/04/07 11:56:42 INFO backup: disabled
2022/04/07 11:56:42 INFO http server: listening on :8000
2022/04/07 11:56:43 INFO IPv6 address of nas.dclife.fun is 2408:832f:20b4:6360::1003 and your IPv6 address is 2408:832f:20b4:6450::1002
2022/04/07 11:56:43 INFO Updating record [domain: dclife.fun | host: nas | provider: dnspod | ip: ipv6] to use 2408:832f:20b4:6450::1002
2022/04/07 11:56:44 ERROR not found
2022/04/07 11:57:49 "GET http://192.168.1.2:8000/ HTTP/1.1" from 192.168.1.105:52270 - 200 2028B in 171.032µs
2022/04/07 12:01:00 "GET http://192.168.1.2:8000/ HTTP/1.1" from 192.168.1.105:52270 - 200 2030B in 133.272µs
2022/04/07 12:01:43 INFO IPv6 address of nas.dclife.fun is 2408:832f:20b4:6360::1003 and your IPv6 address is 2408:832f:20b4:6450::1002
2022/04/07 12:01:43 INFO Updating record [domain: dclife.fun | host: nas | provider: dnspod | ip: ipv6] to use 2408:832f:20b4:6450::1002
2022/04/07 12:01:44 ERROR not found
2022/04/07 12:04:37 "GET http://192.168.1.2:8000/ HTTP/1.1" from 192.168.1.105:52270 - 200 2030B in 134.893µs
```
Configuration:

```json
{
  "settings": [
    {
      "provider": "dnspod",
      "domain": "dclife.fun",
      "host": "nas",
      "token": "ABC",
      "ip_version": "ipv4"
   }, 
    {
      "provider": "dnspod",
      "domain": "dclife.fun",
      "host": "nas",
      "token": "ABC",>>>>>>>>>>Same with IPv4. Do not know if this is correct
      "ip_version": "ipv6"
    }
  ]
}
```

**Comment by jibwf** [comment]
Checked dnspod document, find token incorrect. After correct token, report 'ERROR malformed IP address received'

**Comment by jibwf** [comment]
for both IPv4 and IPv6 record, we need two sections in conf.json right?

**Comment by qdm12** [comment]
Hello, sorry for the huge delay answering.

> Checked dnspod document, find token incorrect. 

Yes there are so many error codes from their API, we pretty much (me and/or people who PR-ed the dnspod changes) focused on handling the success case, and not on reporting the error very nicely.

> After correct token, report 'ERROR malformed IP address received'

23ec8d7907430ceb0a4870b925b789b9f51d0fe6 (pull the latest image) should now log the entire JSON body received as a response when the IP is malformed, so please run that and report back with the JSON body you got. The `value` field with the ip might not even be there because of another error.

> for both IPv4 and IPv6 record, we need two sections in conf.json right?

Yes you should have them as two sections 👍
