### ISSUE TITLE
Feature request: Add provider for INWX

### ISSUE THREAD

**Issue by stelas** [qdm12/ddns-updater#328]
Hej,
thanks for your DDNS updater.
It would be nice to add inwx.com as provider. Their protocol is documented [here](https://kb.inwx.com/de-de/8-dyndns) and the update URL is:
`https://<user>:<passwd>@dyndns.inwx.com/nic/update?hostname=<domain>&myip=<ipaddr>&myipv6=<ip6addr>`

**Comment by qdm12** [comment]
This is being worked on in #379 it should get merged soon :wink:

**Comment by qdm12** [comment]
Done in bd4b87032f6b179ae29cdf6d89b98a8215502df1
