### ISSUE TITLE
Help: Failure (malformed IP address received: ), 4m42s ago

### ISSUE THREAD

**Issue by ZZXPStudios** [qdm12/ddns-updater#334]
I received this error code: Failure (malformed IP address received: ), 4m42s ago

**Comment by qdm12** [comment]
Looks like you got an empty string as a response and the program expected an IP address. What's your DNS provider and the program version you're running?

**Comment by WinkeyCheng** [comment]
I'm using Amazon EC2, and I'm running the latest version of DDNS updater

**Comment by qdm12** [comment]
Yes but what's the dns provider you're trying to send an update to?

**Comment by WinkeyCheng** [comment]
I wanted to update my IP to Namecheap, built on 15th of March

**Comment by qdm12** [comment]
This should be fixed in 88474c8a3af946e7e2140c8cb38de88d89922549

Although I'm not sure why it doesn't return an IP address. I use Namecheap and it does return the IP address as expected.
