### ISSUE TITLE
Feature request: Support for Google Cloud DNS

### ISSUE THREAD

**Issue by orbatschow** [qdm12/ddns-updater#336]
1. What's the feature?

It would be nice to have support for [Google Cloud DNS](https://cloud.google.com/dns)

**Comment by jcfrosty** [comment]
You can use Google DDNS, you just use the dyndns option and point the server to domains.google.com

**Comment by orbatschow** [comment]
This PR introduces [GCP](https://cloud.google.com/) as a provider, which is, at least to my knowledge, something (completely) different than Google Domains.

**Comment by qdm12** [comment]
Hi there, recently I changed the code to not depend on the google sdk for GCP, can you try the latest version please and let me know if it still works fine? Thanks!
