### ISSUE TITLE
Option to force DNS resolution using external DNS provider

### ISSUE THREAD

**Issue by g3rman42** [qdm12/ddns-updater#339]
1. What's the feature?
Toggle to select between native OS DNS resolution (i.e. DNS server configured by the operating system) or 
external provider or external IPs.

2. Extra information?
When using split DNS a host or domain will typically resolve to a private RFC1918 address because the internal DNS server resolves
to the private IP of 10.x.x.x or 192.168.x.x instead of the public NAT IP.
To overcome this it would be ideal to be able to tell the updater which DNS server to use to verify what the host or domain
currently resolves to. For example:

-Resolve current IP using host DNS
-Resolve current IP using (Google (8.8.8.8), Cloudflare (1.1.1.1), or Quad9 (9.9.9.9))

**Comment by g3rman42** [comment]
Can be accomplished by passing "--dns" option to container.

**Comment by qdm12** [comment]
Indeed!

Or

```yml
  dns: 1.1.1.1
```

for docker-compose.yml files.
