### ISSUE TITLE
`desec.io`

### ISSUE THREAD

**Issue by vRobM** [qdm12/ddns-updater#349]
Please add support for the modern https://desec.io

**Comment by cblte** [comment]
This would be nice to have. yes! Bumping +1

**Comment by MrRulf** [comment]
would love to see this too :D

**Comment by qdm12** [comment]
Done this summer with https://github.com/qdm12/ddns-updater/commit/7b3b6609fd89b4133a7a6fdacf1e0a06b3576532

Available in the latest image and future release 2.6
