### ISSUE TITLE
update a TXT record containing an SPF string?

### ISSUE THREAD

**Issue by JuicyFruiter** [qdm12/ddns-updater#356]
Hi,
As a possible feature, I'd like to be able to update a TXT record which is currently in the format:
v=spf1 a mx ip4:example.com ~all

Because the SPF record refers to a domain name instead of an IP address, this is causing a low email reputation.
I'd like to be able to use ddns-updater to update the TXT record to:
v=spf1 a mx ip4:123.123.123.123 ~all

Is this supported already? or if not, can it be integrated, please?

**Comment by qdm12** [comment]
Not supported, but it won't be implemented anytime soon, there is already a huge backlog of issues, I'm the sole maintainer and I'm pretty much out of time continuously. Sorry, maybe one day though!

**Comment by favonia** [comment]
@JuicyFruiter Out of curiosity, why is the `ip4` filter needed when the `a` filter is in use and `A` and/or `AAAA` records are probably updated by ddns-updater?

**Comment by JuicyFruiter** [comment]
Interesting and good spot!  Not an intended inclusion - I used an automatically generated service to generate the SPF record when troubleshooting an issue during initial setup (the issue had been resolved by deleting and re-creating the SPF record from scratch, but at some point I had assumed that the syntax must have been incorrect so used an automatically generated field along the way.)

**Comment by JuicyFruiter** [comment]
Update:  Thanks.  I think that has resolved the need for this feature request.  removing the `ip4` mechanism means the ip address is no longer required 👍
