### ISSUE TITLE
Feature request: AWS Route 53

### ISSUE THREAD

**Issue by pbarone** [qdm12/ddns-updater#375]
1. What's the feature?
Support for AWS Route 53

2. Extra information?

**Comment by willsargent** [comment]
Bump!  This would be amazing!

**Comment by roseap42** [comment]
Agree. I'm looking for a new all-in-one ddns updater, and have a route53 domain that needs to be updated. Great project you've got here!

**Comment by seth586** [comment]
Agreed, would appreciate!

**Comment by qdm12** [comment]
You can build the (beta route53) image with docker and git using:

```sh
docker build -t qmcgaw/ddns-updater https://github.com/marcelohpf/ddns-updater.git#feat/aws-simple-record
```

And then try it following https://github.com/marcelohpf/ddns-updater/blob/feat/aws-simple-record/docs/route53.md

I'm still waiting for feedback to check it works fine, please reply on https://github.com/qdm12/ddns-updater/pull/715 thanks!

**Comment by heisian** [comment]
@qdm12 Thank you for your work on this - excited to use it once it's out of beta!

**Comment by qdm12** [comment]
Whoops sorry I forgot to close the issue this in the latest and v2.7.0 release 😉 See the readme
