### ISSUE TITLE
Feature request: Support Zoneedit.com

### ISSUE THREAD

**Issue by kornface13** [qdm12/ddns-updater#382]
1. What's the feature? Requesting support for zoneedit.com's dynamic dns feature, which required a token.  
https://support.zoneedit.com/en/knowledgebase/article/dynamic-dns

**Comment by AngusNB** [comment]
I would appreciate support for zoneedit also.

**Comment by qdm12** [comment]
Duplicate of #226 

Please try image tag `:pr-482` and report if it works or not on #226 documentation is at https://github.com/qdm12/ddns-updater/blob/zoneedit/docs/zoneedit.md

**Comment by qdm12** [comment]
it's now supported in the latest image, as well as in future release v2.6.0
