### ISSUE TITLE
Bad authentication

### ISSUE THREAD

**Issue by flixxx** [qdm12/ddns-updater#386]
### Discussed in https://github.com/qdm12/ddns-updater/discussions/385

<div type='discussions-op-text'>

<sup>Originally posted by **flixxx** October 24, 2022</sup>
Trying to setup ddns-updater with my provider dynu
logs pulls the right info (current ip, ip logged on their site, domain, etc..)
when it comes time to update it, the following error;
ERROR bad authentication

I tried using my password, ip updater password, md5 hashed password.

</div>

**Comment by JackTalisker** [comment]
Same problem
Debug posted at #385

**Comment by qdm12** [comment]
A bit confusing from their documentation: https://www.dynu.com/en-US/DynamicDNS/IP-Update-Protocol

Basically you can use `hostname=subdomain.domain.com` but they also have a section on *alias/subdomain* saying to use `alias=subdomain` and hostname. The fix as @JackTalisker suggests in #385 is to just use `hostname=subdomain.domain.com` and not `alias`.

Anyway fixed it in the latest image to use only `hostname` and not `alias`.
