### ISSUE TITLE
Unraid 6.11.1  ERROR open /updater/data/updates.json: permission denied

### ISSUE THREAD

**Issue by Michi202020** [qdm12/ddns-updater#387]
Hello,

in the new version of Unraid can i not start the container.
In the Protokoll i become this:
ERROR open /updater/data/updates.json: permission denied

What can i do?

Best Regards
Michael

**Comment by qdm12** [comment]
You need to change the permissions of your bind mounted directory on your host system, see the readme. Copy pasted:

```sh
mkdir data
touch data/config.json
# Owned by user ID of Docker container (1000)
chown -R 1000 data
# all access (for creating json database file data/updates.json)
chmod 700 data
# read access only
chmod 400 data/config.json
```

You will probably need a shell to do that on Unraid as far as I know.
Alternatively you can set the json on a single line in the env variable `CONFIG` (also see the readme).
