### ISSUE TITLE
Feature request: ...Support for all-inl.com

### ISSUE THREAD

**Issue by horschte** [qdm12/ddns-updater#399]
1. What's the feature?
Hi, can you add support for all-inkl.com?

Host                                            - my.subdomain.com
Update-URL                               -  dyndns.kasserver.com/
Update-URL with IP                 - dyndns.kasserver.com/?myip=<ipaddr>
Update-URL with IPv4 & v6    - dyndns.kasserver.com/?myip=<ipaddr>&myip6=<ip6addr>
Username                                 - xxxxxxxx
Password                                   - xxxxxxxxx
 
fritzbox router example
https://all-inkl.com/img/anleitungen/9571_de.png

best regards

**Comment by qdm12** [comment]
Supported since https://github.com/qdm12/ddns-updater/commit/584597d5cb8c5ce8edfc9f5f15a387e1932ab174

My bad, it was missing from the readme, added it in 46b1d649f0942de1c04fae42b656e7b68053ba74
