### ISSUE TITLE
Unable to open database file.....

### ISSUE THREAD

**Issue by danmed** [qdm12/ddns-updater#4]
2019/04/29 15:36:32 Info: Node 0: Found 1 records to update
#################################
######## Give some ❤ at #########
# github.com/qdm12/ddns-updater #
#################################
2019/04/29 15:36:32 Info: Node 0: unable to open database file

**Comment by danmed** [comment]
I'm an idiot.

**Comment by qdm12** [comment]
Don't be harsh on you, it happens to all of us 😄 

However, did the line `2019/04/29 15:36:32 Info: Node 0: Found 1 records to update` came before the rest? That seems odd and should not happen 🤔

**Comment by danmed** [comment]
I may have incorrectly copied the output.. I had simply forgotten to set
permissions on the data folder :)

**Comment by UntouchedWagons** [comment]
What did you do to fix this? I'm having the same issue and have no idea what the problem is. https://xkcd.com/979/

**Comment by qdm12** [comment]
Please post back the output from `ls -l` on the directory containing the database file to see permissions and ownership.

Merry Christmas :christmas_tree: !

**Comment by UntouchedWagons** [comment]
$ls -l /docker/ddns-updater 
    total 5
    -rw-r--r-- 1 root root 295 Dec 25 02:09 config.json

**Comment by qdm12** [comment]
Yes it's owned by `root` that's why it doesn't work.

Run this to make it owned by user ID 1000 and group ID 1000:

```sh
chown 1000:1000 /docker/ddns-updater/config.json
```

**Comment by UntouchedWagons** [comment]
Still says `unable to open database file {"node_id": 0}`

**Comment by qdm12** [comment]
If you bind mount the directory, you have to change the ownership of the directory too, forgot to mention. In my case I only bind mount the config file.

Most containers out there use the root user by default, which is dangerous as anyone getting access to the container can almost do anything your host root user can do, see [this for more information for example](“Processes In Containers Should Not Run As Root” by Marc Campbell https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b).

Sometimes root user is needed (i. e. run a VPN) but 90% of the time it's not.

The disadvantage is that you have to match the bind mounted files with the user running the container. Note that you can change the user running the container with `--user=1001:1001` for example or `--user="root"`.
