### ISSUE TITLE
Bug: HEAD request not supported

### ISSUE THREAD

**Issue by StrongWind1** [qdm12/ddns-updater#409]
**TLDR**: *HTTP HEAD requests fail*

1. Is this urgent: No
2. DNS provider(s) you use: N/A
3. Program version: latest built on 2022-12-14T20:23:40Z (commit 3fd82ab)
4. What are you using to run the container: docker-compose
5. Extra information (optional):
I need these enabled for my status checker to report that the website is up and working. Why are HEAD requests disabled? They are smaller then GET requests.

Logs:

```
2023/01/06 20:03:56 "HEAD http://192.168.X.X:8000/ HTTP/1.1" from 172.17.0.1:38214 - 405 0B in 13.137µs
2023/01/06 20:05:02 "HEAD http://192.168.X.X:8000/ HTTP/1.1" from 172.17.0.1:42664 - 405 0B in 6.462µs
```

Configuration file:

```
{
    "settings": [
      {
        "provider": "duckdns",
        "host": "XXX",
        "token": "XXX",
        "ip_version": "ipv4",
        "provider_ip": false
      }
    ]
}
```

Curl:
XXX@XXX # curl -I http://192.168.X.X:8000
HTTP/1.1 405 Method Not Allowed
Date: Fri, 06 Jan 2023 20:14:29 GMT

Host OS: Debian 11

**Comment by qdm12** [comment]
There is no web API for now, subscribe to #178 😉 For now it's just a web ui served on port 8000.
I'm very much lagging behind on this project so please be patient 🙏
