### ISSUE TITLE
Add netcup.net

### ISSUE THREAD

**Issue by salapate** [qdm12/ddns-updater#415]
1. What's the feature?
New DDNS provider.
https://ccp.netcup.net/run/webservice/servers/endpoint.php

2. Extra information?
Netcup offers a variety of hosting services. Along with that they also expose their DNS by means of an API which easily can be used for implementing a DDNS service.

Example implementation in PHP:
https://github.com/stecklars/dynamic-dns-netcup-api

**Comment by Assaro** [comment]
Someone already wrote an implementation using GO: [https://github.com/Hentra/dyndns-netcup-go](https://github.com/Hentra/dyndns-netcup-go)
This might cut down on implementation time if actually done

**Comment by qdm12** [comment]
- There is an ongoing PR #361 for this
- This issue duplicates #282 please subcribe to that one instead to be notified when this is merged.
