### ISSUE TITLE
Feature request: Additional provider do.de (Domain Offensive)

### ISSUE THREAD

**Issue by benediktheyer** [qdm12/ddns-updater#419]
1. What's the feature?
It would be really cool if the provider do.de (Domain Offensive) was implemented.

2. Information provided for fritz-box:
* Update-URL: https://ddns.do.de/?myip=<ipaddr>
* domainname, e.g. subdomain or @
* username
* password

**Comment by qdm12** [comment]
Duplicate of #310 please subscribe to that one instead (pasted your content over there)
