### ISSUE TITLE
Bug: shoutrr matrix error: title is not a valid config key

### ISSUE THREAD

**Issue by Its-EGS** [qdm12/ddns-updater#427]
Hi Team,

I am trying to reach my matrix room via SHOUTRR_ADDRESSES in docker-compose but I always get the following error:
`ERROR matrix: title is not a valid config key [disabletls rooms]`

This problem is already known and solved at https://github.com/containrrr/shoutrrr/issues/202.  I suspect that shoutrrr just needs to be updated in the package.

**Comment by qdm12** [comment]
This should be fixed since 5fff4f4a564f0b59ba4ab4db16e370fe26f42a39 which is part of image `:v2.5.0` and the latest image.
