### ISSUE TITLE
Web UI Typo

### ISSUE THREAD

**Issue by craigkc** [qdm12/ddns-updater#43]
In the web UI the last (far right) column header reads "Previous IPs (achronologically)" which appears to be a simple typo, as it appears it should be "chronologically" (omitting the leading 'a').

**Comment by qdm12** [comment]
I think the left most IP address is the most recent one, so it's reverse chronological. Or I did a coding mistake... 

But you're right that achronological means not chronological which is not the case here. I'll search for a better word :smile:
