### ISSUE TITLE
Feature request: Please add a simple authencation method, so not anybody can visit the DNS list

### ISSUE THREAD

**Issue by xmdedady** [qdm12/ddns-updater#439]
1. What's the feature?
  The home enviromnet always not a hight security Lan environment, please consider to add a simple authencation method to the web site,  event it is the BASIC authencation, thanks

2. Extra information?

https://github.com/qdm12/ddns-updater/discussions

-->

**Comment by fredericrous** [comment]
use authelia to protect your endpoints
https://www.authelia.com/

I don’t think ddns-updater should implement auth security

**Comment by qdm12** [comment]
As @fredericrous says, and also subscribe to #191 this issue is a duplicate.
