### ISSUE TITLE
Feature request: Add provider WIX

### ISSUE THREAD

**Issue by apxamccallum** [qdm12/ddns-updater#450]
1. What's the feature?
Please add WIX to supported DNS providers
2. Extra information?
I believe this is the relevant documentation for WIX api:
https://dev.wix.com/api/rest/account-level-apis/domain-connections/connect-domain

**Comment by apxamccallum** [comment]
On further reading, it looks like this allows you to connect domains from other providers to Wix. I'm thinking this might not be possible :-/

**Comment by qdm12** [comment]
Yeah I don't think Wix is a domain name seller right? (from the top of my head)
I'm going to close this early, but feel free to copy pasta and create another issue if you think this is possible in the end.
