### ISSUE TITLE
Feature request: Add provider all-inkl.com

### ISSUE THREAD

**Issue by black-guardian** [qdm12/ddns-updater#453]
1. Is it possible to add another Proiver? In my case it is all-inkl.com

2. Extra information?
Host : yourdomain.com
Update-URL : dyndns.kasserver.com/
Update-URL with IP : dyndns.kasserver.com/?myip=<ipaddr>
Update-URL with IPv4 & v6 : dyndns.kasserver.com/?myip=<ipaddr>&myip6=<ip6addr>
Usrname : yourusername
Password : yourpassword

**Comment by qdm12** [comment]
Allinkl is already supported, see https://github.com/qdm12/ddns-updater/blob/master/docs/allinkl.md
