### ISSUE TITLE
Feature request: Release containers with a version tag

### ISSUE THREAD

**Issue by stavros-k** [qdm12/ddns-updater#464]
1. What's the feature?

Latest versioned tag is v2.4.1 from 2y ago. It would be great to have a fresh tagged release.
It's a best practice to use tagged containers instead of `latest`. 
That would help also with bug reports knowing what version a user is running.

Also kinda relevant:
More frequent versioned releases.

Thanks!

2. Extra information?

**Comment by stavros-k** [comment]
I see there is now a tagged image https://hub.docker.com/layers/qmcgaw/ddns-updater/v2.5.0/images/sha256-834268eaa69c802e51e9fa377074fc95ccf58201a2592126367b1a072369d7d7?context=explore
I assume this is now fixed?

**Comment by qdm12** [comment]
> Latest versioned tag is v2.4.1 from 2y ago. It would be great to have a fresh tagged release.

100% definitely, super shame on me, long overdued release finally done!

> It's a best practice to use tagged containers instead of latest.

Well not necessarily. From a user perspective, maybe, but from a maintainer perspective and to have more stable releases, having users use the latest image does help 😉 I actually wrote this up to explain my strategy after reading your issue 😄: https://qqq.ninja/blog/post/docker-tags/

> That would help also with bug reports knowing what version a user is running.

Yes, although the commit is written to the built Docker image so this helps a bit too even with the latest image. Obviously a semver is much easier to comprehend than a commit hash.

> More frequent versioned releases.

Again, for sure, I'll aim at monthly releases from now on 👍
