### ISSUE TITLE
Unhealthy IP Lookup for Cloudflare proxied domains.

### ISSUE THREAD

**Issue by Chewza** [qdm12/ddns-updater#47]
When utilizing an A record for dynamic DNS on a proxied CloudFlare domain, the following is seen constantly in the console log.

`WARN    unhealthy: lookup IP address of MyDomain.com is 104.18.55.237 instead of W.X.Y.Z      {"node_id": 0}
`
Note that 104.18.55.237 is the CloudFlare proxy IP and W.X.Y.Z is my current Public IP.

I'm utilizing OpenDNS for the IP lookup.

**Comment by qdm12** [comment]
Interesting, what happens when you run

```sh
docker run -it --rm alpine:3.11 nslookup MyDomain.com
```

What's the IP address?

For now, the healthcheck lookup only resolves your domain.com and checks the IP resolved matches your current public IP address. Maybe it should be tweaked for proxied domain, I'm not sure how to approach that yet.

**Comment by Chewza** [comment]
Output of that command is the CloudFlare proxied IP address, not my public IP address which is the expected outcome.

The only way I could see health check working on a proxied CloudFlare domain in the config, is logic could be implemented to pull the IP configured for that domain from the CloudFlare API, and compare with the IP from an IP health check. If different, update the domain record, if not move along.

**Comment by qdm12** [comment]
For now you can set `"no_dns_lookup": false` for that record to avoid the DNS lookup part of the healthcheck. The healthcheck also verifies the latest state of the update, and will mark the container as unhealthy if any update failed for whatever reason. I think that should be enough.

And yes, the healthcheck is only informational, it doesn't retry on failure.

The only thing I'll dig into in the coming days is why the DNS lookup does not work only for `@` host proxy records for Cloudflare, but I might need your help on that one 😉  I'll post back here once I'm into it.

Thanks!

**Comment by Chewza** [comment]
Your efforts are much appreciated! Happy to help when you're ready!

**Comment by Chewza** [comment]
FYI. Adding that suggested boolean to the domain code block in question doesn't seem to affect the outcome. I'm still receiving the errors.

![2020-04-08_17-01-25_3xpB0BjdWG](https://user-images.githubusercontent.com/8115774/78833337-b2de1c00-79ba-11ea-9afb-1875d4ca449f.png)

`2020-04-08T17:02:08.267-0400	WARN	unhealthy: lookup IP address of MyDomain.com is 104.18.55.237 instead of 72.84.xx.xx	{"node_id": 0}
`

**Comment by qdm12** [comment]
You need to set `"no_dns_lookup": true`, sorry about that little mistake 😉
