### ISSUE TITLE
Feature request: ...

### ISSUE THREAD

**Issue by Into69** [qdm12/ddns-updater#479]
1. What's the feature?
Support for easydns

2. Extra information?
You can send the following parameters in the QUERY_STRING of a request, for example:

https://username:dynamictoken@api.cp.easydns.com/dyn/generic.php?hostname=example.com&myip=10.0.0.2

If you do not include the myip parameter, our update script will look to the IP the request originates from and update to that.

**Comment by qdm12** [comment]
Duplicate of #421
