### ISSUE TITLE
Container stops after June 12 update

### ISSUE THREAD

**Issue by 5tring3r** [qdm12/ddns-updater#484]
After the update the container stops

1. No
2. namecheap
3. Program version: version latest built on an unknown date (commit 4b51c8b)
4. What are you using to run the container: docker-run (synology)
5. Extra information (optional)

Logs:

ext:qtip="2023-06-13T13:20:57Z ERROR settings validation: health settings: server listening address: splitting host and port: address 10s: missing port in address

Configuration file (**remove your credentials!**): provided in env variable

Host OS: Synology 920+

**Comment by qdm12** [comment]
Pull the latest image again, it will fix it. That was a buggy latest image that stayed around for a few hours yesterday, it's already fixed 😉

**Comment by 5tring3r** [comment]
> Pull the latest image again, it will fix it. That was a buggy latest image that stayed around for a few hours yesterday, it's already fixed 😉

Thank you. Works
