### ISSUE TITLE
Truenas ddns-updater v2.5.0_1.0.6

### ISSUE THREAD

**Issue by nxydyxsj123456** [qdm12/ddns-updater#489]
aliyun  cannot get record ID: bad HTTP status: 400
![屏幕截图 2023-06-15 151330](https://github.com/qdm12/ddns-updater/assets/32428837/db17fec7-5c13-4ac1-91fb-48f7d737aabd)

can anyone help me

**Comment by qdm12** [comment]
What version are you running? You can find at the beginning of the logs.
