### ISSUE TITLE
Feature request: Hetzner API

### ISSUE THREAD

**Issue by AbsusRex** [qdm12/ddns-updater#493]
1. What's the feature?

Would love to see support for Hetzner

2. Extra information?
API doc: https://dns.hetzner.com/api-docs
And there's also this existing project https://github.com/kutzilla/docker-hetzner-ddns/tree/master

**Comment by qdm12** [comment]
Done in 301e4d6cc4a4fe19da28a6c64025c6c840979ba8 for the latest Docker image. Thank you for your patience!!
