### ISSUE TITLE
Cloudflare Update removes "Proxied" setting.

### ISSUE THREAD

**Issue by qwacko** [qdm12/ddns-updater#5]
When this tool updates the IP address of a cloudflare DNS entry, the fact that the domain is being proxied (or passed through the cloudflare CDN) is cancelled, exposing the target IP address directly to the internet. 

I have tried this a few different ways, but this always seems to be the case.

**Comment by qdm12** [comment]
I am not sure what you are saying, but it is very likey related to the `proxied` option that you can see [here in the Cloudflare API](https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record) 

> Whether the record is receiving the performance and security benefits of Cloudflare

If this is what you need, I'll promptly add it to the configuration options so you can use it. Let me know if this is what you are talking about. Thanks !

**Comment by qwacko** [comment]
Yes you are right that is the correct point. I did a little testing and the "proxied" parameter is currently being set to false by the updater, but it should instead store the current value and retain it. If this isn't possible then I guess a setting in the config.json file would be best.

**Comment by qdm12** [comment]
I have added the `proxied` parameter. Simply add it to the JSON file as boolean like so:

```json
{
  "provider": "cloudflare",
  ...
  "proxied": true
}
```
