### ISSUE TITLE
Bug: Mistake in doc INWX

### ISSUE THREAD

**Issue by CoolxFrog** [qdm12/ddns-updater#519]
Hello

https://github.com/qdm12/ddns-updater/blob/master/docs/inwx.md

at the line
      "ip_version": "ipv4",
is a comma, but its the last setting
better would be:
      "ip_version": "ipv4"

Regards
Chris

**Comment by qdm12** [comment]
Indeed, thanks for reporting this!

Fixed in ec1ee7803b013b45a6efb086bd670afe7c91cdb9 (for inwx and also nowdns it turns out!)
