### ISSUE TITLE
Cannot change env. variables in docker container (must fill fields), 

### ISSUE THREAD

**Issue by Matis-11** [qdm12/ddns-updater#520]
Docker installaton synology:

When I want to change e.g. just the period or cooldown_ period, it is not possible to save the variable settings as the fields: CONFIG, RESOLVER_ADDRESS, SHOUTRRR_ADDRESSES, TZ cannot left empty as they are must fill field.
So I cannot make any changes to the standard config.

**Comment by Matis-11** [comment]
I could just delete the empty fields and save it then, but I think this is just a workaround.

**Comment by qdm12** [comment]
> cannot left empty as they are must fill field.

They are not, each of the ones you mentioned are empty by default and  can be left empty. Check out the env variables lines after https://github.com/qdm12/ddns-updater/blob/7fac178b7dd76d6f3576328f3831ea010e954bc1/Dockerfile#L72

I'm missing information, I guess you use some wrapper like unraid template around the docker image, and that wrapper configuration is wrong? 🤔

**Comment by qdm12** [comment]
Sorry this workaround will have to do until Synology fixes it, I need to keep the environment variables (even without default value) in the Docker image for documentation purposes (i.e. `docker inspect qmcgaw/ddns-updater`).
