### ISSUE TITLE
Help: api.godaddy.com is blocked by GFW(great firewall)

### ISSUE THREAD

**Issue by BH1SCW** [qdm12/ddns-updater#531]
**TLDR**: *Describe your issue in a one liner here*

1. Is this urgent: Yes
2. DNS provider(s) you use: godaddy
3. Program version:

    

    `Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)`

4. What are you using to run the container: docker-compose
5. Extra information (optional)

Logs:

```log
ddns-updater    | 2023/09/23 01:15:48 ERROR Put "https://api.godaddy.com/v1/domains/xxxx/records/A/code": read tcp 172.17.0.2:33696->23.13.187.70:443: read: connection reset by peer
```

Host OS: ubuntu

This is not bug of ddns-updater, but still want to get help here
I tried to use 
```HTTP_PROXY: 'http://host:port'
      HTTPS_PROXY: 'http://host:port'
      NO_PROXY: 'localhost, *.test.lan'
```

but still now work,  any other suggestion? Thanks

**Comment by qdm12** [comment]
Closing this since irrelevant to the project.
You can use a VPN container such as Gluetun (I'm the maintainer) and connect ddns-updater through Gluetun, that might work. Good luck!
