### ISSUE TITLE
DNS Provider Hetzner

### ISSUE THREAD

**Issue by webobardewisch** [qdm12/ddns-updater#534]
Hi there,
is it possible to add Hetzner (hetzner.com) as DNS provider?

Thanks
Regards

Werner

**Comment by miklosbagi** [comment]
+1 :) I'm using some old code to deal with this.

**Comment by qdm12** [comment]
Done in 301e4d6cc4a4fe19da28a6c64025c6c840979ba8 for the latest Docker image.

**Comment by varac** [comment]
@qdm12 Thanks! Do you mind releasing a new version with Hetzner support ?
