### ISSUE TITLE
Backup config.json periodically

### ISSUE THREAD

**Issue by CygnusHyoga** [qdm12/ddns-updater#54]
Hi, I always run a backup for the ddns-updater configuration. But in the last version the shell /bin/sh is not found in the docker image. Is there any change that broke the sh shell in the latest release?

```
oc rsh ddns-updater-x-xxx /bin/sh -i -c 'tar -zcvf /backup/ddns-updater.apps.xxx.com.ar/ddns-updater.20200501.tar.gz /updater/data'

rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:235: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
```

Thanks!!

**Comment by qdm12** [comment]
The image is now based on Scratch (no OS, just some files + static binary and access to the Kernel) as Alpine isn't needed anymore (it was for sqlite).

You can run that backup command on your host OS provided you bind mounted the data directory. 

Alternatively I can add some code to backup your data is a tar file periodically?

**Comment by CygnusHyoga** [comment]
Thanks qdm for the reply. Wow great new to migrate the image to scratch, it's really small :-)

It will be really great if you can add some code to make a backup periodically!! Thanks again

**Comment by qdm12** [comment]
Hi again, I have some thoughts on your backup, what exactly do you want to backup? The data/updates.json? Because your config.json should be quite constant right? I don't really see the point in backing up something not changing; maybe you want to back it up to another destination?

**Comment by CygnusHyoga** [comment]
Hi, I backup the /udater/data/* folder, which includes: config.json, updates.json and the update.db. In case of some update goes wrong or some config change break the container. 

Yes, I backup all the configuration to another location, I have a shared PV for backup, in a remote location for safe backup.

**Comment by qdm12** [comment]
Ok thanks. updates.db is the old database for sqlite, which is now migrated to updates.json so you can safely delete it. I'll set something to periodically tar updates.json and config.json, indeed it's a good idea if a coding monkey (=me) breaks something :wink:

**Comment by CygnusHyoga** [comment]
you have to be always careful in this life :-) Thanks!

**Comment by qdm12** [comment]
Would a zip file with the name ddns-update-data-<date+timestamp>.zip be ok? Or tar.gz is a must for some reason? I feel zip is more supported across platforms.

**Comment by qdm12** [comment]
I added the feature using zip files, you can now specify `BACKUP_PERIOD=24h` for example, together with `BACKUP_DIRECTORY=/yourpath` (note that this is inside the container, not on your host). It will create a zip file containing updates.json and config.json together, with the unix nanoseconds timestamp so you can sort the filenames.

**Comment by CygnusHyoga** [comment]
Yes, podname(tag app=name)+date+timestamp is what I being used, ddns-update-data-<date+timestamp>.zip it's fine because now we don't have to run external job with the podname :-). I've no reason for tar format, you are right he zip format is more standard across platforms. Thanks Qdm!!, I will try the new feature and comment!

**Comment by CygnusHyoga** [comment]
I confirm...It's working great!!! A big, big, big thanks!!!

**Comment by qdm12** [comment]
Glad it works :+1: Enjoy!
