### ISSUE TITLE
Feature request: Please add DynV6 (Free Dynamic DNS)

### ISSUE THREAD

**Issue by arcadiabay** [qdm12/ddns-updater#550]
1. What's the feature?
Could you add Dynv6 provider as possible choice ?

2. Extra information?
Documentation is here : https://dynv6.com/docs/apis

**Comment by MitjaHenner** [comment]
https://github.com/qdm12/ddns-updater/blob/master/docs/dynv6.md#domain-setup
Seems like it's already working.

**Comment by qdm12** [comment]
Fixed by #549 thanks 😉
