### ISSUE TITLE
Feature request: Add www.goip.de to the supported providers

### ISSUE THREAD

**Issue by diestrohs** [qdm12/ddns-updater#563]
Hi,

could you please add www.goip.de to the supported providers.

Thank you very much and best regards

**Comment by kupernikus87** [comment]
Ohh, i See your requeast to late and have Open a own requeat for the same.
https://github.com/qdm12/ddns-updater/issues/581

Hope they will add them in Future.

**Comment by qdm12** [comment]
Let's keep #581 opened instead of this one, due to the extra content (thanks @kupernikus87 for the effort)
@diestrohs feel free to subscribe to #581 to be alerted when it's done.
