### ISSUE TITLE
Feature request: Disable WebUI and output into console/log

### ISSUE THREAD

**Issue by PassiveLemon** [qdm12/ddns-updater#565]
1. What's the feature?
A setting to disable the WebUI and output update information into the log

2. Extra information?
I would just like to reduce unnecessary web apps and I feel this app could function well enough by viewing the output in the Docker logs

For a rough idea on the log output could look like:
`{ "porkbun" - "any.domain.com" } Update Successful (xx.xxx.xxx.xx)`

**Comment by qdm12** [comment]
It's already logged by default when an ip address changes for example. Otherwise you can set the log level to debug but that might be too much logs (logs every update / check).

For the web ui, just don't publish the port and that's it, it won't consume any cpu cycles if no-one accesses it 😉

**Comment by PassiveLemon** [comment]
Ah I see, I wasn't aware that it already outputted into the log. I gave it a little test by changing the IP of my domain to something slightly different and I see that it only outputs to the log when it's updated!
