### ISSUE TITLE
Please Support dynDNS for IONOS

### ISSUE THREAD

**Issue by dwillerstri** [qdm12/ddns-updater#566]
1. What's the feature?
DynDNS Support for IONOS
2. Extra information?

**Comment by kuronashi** [comment]
Please add this.

**Comment by qdm12** [comment]
**Duplicate issue of #194**

It should be done in commit ff5767aa382b34964d5963d49a9f72a857b3a87d (latest image, and future release image `:2.6.0`).
If it doesn't work, please open a new issue, thanks!
