### ISSUE TITLE
Feature request: healthchesk configuration to send updates to every UPDATE_COOLDOWN_PERIOD even if no IP change has been detected

### ISSUE THREAD

**Issue by maxiride** [qdm12/ddns-updater#578]
1. What's the feature?
As of now the SHOUTRRR notification is triggered only if there is an update (eg. IP change), this implementation is useful to know **if and when** an IP change as been detected.

It would be nice to also keep monitored **if the process occurred** with systems like https://healthchecks.io where a listener is configured to expect a "ping" and if it doesn't occur a warning is raised.

2. Extra information?
https://healthchecks.io like other SHOUTRRR  endpoints, simply expect an HTTP POST.

The feature should ping the external system only if ddns-updater successfully completed a work cycle and even if no IP change was detected but the DNS lookup worked.

**Comment by qdm12** [comment]
That's a cool tool I wasn't aware of! 👍 
Is it always an https get request to https://hc-ping.com/xxx ? Right now I'm thinking to just have a HEALTHCHECKSIO_UUID configuration to do so, but I can make it a full URL if necessary.

**Comment by qdm12** [comment]
It should be done in commit 91741a5aad4d30e0fda92521e67651d8864bfd57 (latest image and future release v2.6.0).
Use `HEALTH_HEALTHCHECKSIO_UUID` to set your uuid.

**Comment by maxiride** [comment]
That was quick! Didn't even manage to reply to the first question 😄
