### ISSUE TITLE
Feature request: I'd like to see support for IONOS

### ISSUE THREAD

**Issue by Der-Mitdenker** [qdm12/ddns-updater#580]
1. What's the feature?
Added dyndns support for IONOS

3. Extra information?
Pretty famous provider at least in Germany. ionos.de
They have an API for DNS updates.
https://www.ionos.com/help/domains/configuring-your-ip-address/set-up-dynamic-dns-with-company-name/

**Comment by qdm12** [comment]
**Duplicate issue of #194**

It should be done in commit ff5767aa382b34964d5963d49a9f72a857b3a87d (latest image, and future release image `:2.6.0`).
If it doesn't work, please open a new issue, thanks!
