### ISSUE TITLE
Feature request: Goip.de

### ISSUE THREAD

**Issue by kupernikus87** [qdm12/ddns-updater#581]
1. What's the feature?
Iam using the Provider Goip.de, ITS a German free Service. I Hope you will implement this in Future. thx

2. Extra information?
Under https://www.goip.it/update-url.html are the Update link informations they Support Ipv4 & ipv6
Simple way for Update is

https://www.goip.de/setip?username=[User]&password=[Pass]&subdomain=[subdomain.goip.de]

This Service Support multiple Endpoints(Wan IP) every Endpoints become a own Login and Password as Subprofile.

 I create a subprofile for updating into my profile
You can use this if you need.

Username: toYRQs9GMuXdGJD
Password: X7mCzK4dzJur7kr
Subdomain: dns-updater.goip.de

I used this Service for years and hope you will add them in Future.

Google translate link for url setup
https://www-goip-de.translate.goog/update-url.html?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp

**Comment by qdm12** [comment]
Awesome 🎉  I am rather active currently on this repository, so I should be quick at PR-reviewing 😉
I'm also working on release notes (180 commits ouch) for a 2.6 release, maybe your addition can fit in!

**Comment by CyberAustin** [comment]
So, no pressure then lol

**Comment by CyberAustin** [comment]
Mostly have this working. Just collecting different error types, translating to English and then catching errors. Hopefully submit the PR by the end of the (Central European Time).

**Comment by qdm12** [comment]
No pressure, the release notes are eating a lot of time, it'll likely wait until tomorrow noon (CET) 😄

**Comment by CyberAustin** [comment]
[PR created](https://github.com/qdm12/ddns-updater/pull/623)
