### ISSUE TITLE
Cloudflare ttl error

### ISSUE THREAD

**Issue by Marketos-Damigos** [qdm12/ddns-updater#59]
Hello,

After using ddns-updater for a while with godaddy i wanted to change nameservers and use cloudflare.

I configured it as shown below:

>              "provider": "cloudflare",
>              "zone_identifier": "***********",
>              "identifier": "***********",
>              "host": "***********",
>              "ttl": "1s",
>              "email": "***********",
>              "ip_method": "cycle",
>              "key": "***********"

and i receive the following error:

> 2020-05-21T17:48:16.453Z WARN The value for the duration period of the updater does not have a time unit, you might want to set it to "300s" instead of "300" {"node_id": 0}
> 
> 2020-05-21T17:48:16.455Z ERROR json: cannot unmarshal string into Go struct field settingsType.settings.ttl of type uint {"node_id": 0}
>

**Comment by qdm12** [comment]
ttl should be an integer only, so: `"ttl": 1`. You should set it to something higher like 3600 (one hour). This is not the update period of the program, that one is set with the environment variable `DELAY=300s`.

Feel free to re-open if it doesn't work. Thanks!
