### ISSUE TITLE
Docker on Raspberry Pi 3

### ISSUE THREAD

**Issue by dado991** [qdm12/ddns-updater#6]
Hi,
i'm trying to run the container over a raspberry pi 3b, but i'm getting this error when i start the container.

`standard_init_linux.go:207: exec user process caused "exec format error"`

Googling i read that seems to be a architecture error, do you provide a container builded for arm devices?

Thanks!

**Comment by qdm12** [comment]
I'm working on it, should be ready in 10 minutes top 🚀  You're the first person to ask me about ARM devices, time to do it then  😄

**Comment by dado991** [comment]
Wow! Nice! Thank You so Much!  😄

I will gladly test it!

**Comment by qdm12** [comment]
Ok so it took me longer, I never did this for a Go program 😄 

It's at the number 4 of this [section](https://github.com/qdm12/ddns-updater#setup) of the readme. 

Let me know if it works out!

I think your achitecture is ARM32v7 but it could also be ARM64v8, not too sure unfortunately.

**Comment by qdm12** [comment]
Note I just re-updated the instructions so it's simpler. If you have ARM32v7, try

```sh
docker build -t qmcgaw/ddns-updater \
--build-arg BASE_IMAGE_BUILDER=arm32v7/golang \
--build-arg BASE_IMAGE=arm32v7/alpine \
--build-arg GOARCH=arm \
--build-arg GOARM=7 \
.
```

or all in one line...

```sh
docker build -t qmcgaw/ddns-updater --build-arg BASE_IMAGE_BUILDER=arm32v7/golang --build-arg BASE_IMAGE=arm32v7/alpine --build-arg GOARCH=arm --build-arg GOARM=7
```

**Comment by qdm12** [comment]
Hi there,

Sorry I made a little mistake, I put `.` instead of `https://github.com/qdm12/ddns-updater.git` for the Docker build. I corrected the instructions above and in the readme, so it should work now.

Thanks!
