### ISSUE TITLE
FEATURE REQUEST: allowing setting PUID/GUID

### ISSUE THREAD

**Issue by bcurran3** [qdm12/ddns-updater#60]
Of course I did NOT follow the instructions for setting up the config.json...

After initial install and run I instantly received:
![image](https://user-images.githubusercontent.com/14026600/82609259-06728680-9b71-11ea-9800-dcacaf9ab6ba.png)

If we could set PUID/GUID in the environment variables, setup would be simpler. (HINT: Look at all the linuxserver containers.)

Not sure of the setup, but running as root would also solve the problem!

**Comment by qdm12** [comment]
Linuxserver containers do run as root and then drop it, which is less secured (although better than just root). What you can do however is run the container with a certain user id and group id which achieves the same thing but runs entirely with that user+group, I have a note in the readme for that :wink:

> You could change the user ID, for example with 1001, by running the container with --user=1001

On docker-compose, see [this](https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir)

**Comment by bcurran3** [comment]
I intercommunicated.

Honestly I don't care if the program runs as DonaldJTrump in the children group. This is really a continuation of a theme... to get rid of:

> touch data/config.json
> # Owned by user ID of Docker container (1000)
> chown -R 1000 data
> # all access (for creating json database file data/updates.json)
> chmod 700 data
> # read access only
> chmod 400 data/config.json

I'm hoping #61 and/or #62 will accomplish the same goal. :->
