### ISSUE TITLE
Bug: Infomaniak unknown response received

### ISSUE THREAD

**Issue by OkeOyibo** [qdm12/ddns-updater#604]
The response from the Infomaniak api does not meet expectation anymore.

1. Is this urgent: Yes
2. DNS provider(s) you use: Infomaniak
3. Program version:
"Running version latest built on 2024-01-20T08:56:43.256Z (commit f8bb927)"

4. What are you using to run the container: docker-compose
5. Extra information (optional)
[Bug location: https://github.com/qdm12/ddns-updater/blob/master/internal/provider/providers/infomaniak/provider.go](https://github.com/qdm12/ddns-updater/blob/f8bb927de621e654f2637d0c20eb36db823dbd04/internal/provider/providers/infomaniak/provider.go#L133)

Logs:

```log
2024-01-21T13:59:52+01:00 ERROR unknown response received: successfully_changed 109.202.196.157
2024-01-21T14:09:50+01:00 ERROR unknown response received: no_change 109.202.196.157
```

Configuration file (**remove your credentials!**):

```json
{
        "settings": [
                {
                        "provider": "infomaniak",
                        "domain": "xxx",
                        "host": "@",
                        "username": "xxx",
                        "password": "xxx",
                        "ip_version": "ipv4",
                        "provider_ip": true
                },
                {
                        "provider": "infomaniak",
                        "domain": "xxx",
                        "host": "@",
                        "username": "xxx",
                        "password": "xxx",
                        "ip_version": "ipv4",
                        "provider_ip": true
                }
        ]
}
```

Host OS: Unraid

**Comment by qdm12** [comment]
Thanks for taking the time to report this! 👍 
This should be fixed to handle these new prefixes in the latest image 😉
