### ISSUE TITLE
updater for Squarespace domains

### ISSUE THREAD

**Issue by brunsc** [qdm12/ddns-updater#605]
Google domains (on the list) has been sold to Squarespace domains, which doesn't have ddns support.

**Comment by qdm12** [comment]
Thank you @brunsc for creating the issue and @Zeustopher for the very detailed comment 💯 

The google provider was removed, documentation updated, and the program returns an error if someone uses the google provider.

**Comment by carnifux** [comment]
Google haven't moved over all the domains yet. If this change broke your dns like it did mine (thanks), tag v2.5.0 was the last working one.
