### ISSUE TITLE
Feature request: rename `host` -> `owner`

### ISSUE THREAD

**Issue by qdm12** [qdm12/ddns-updater#625]
The current parameter `host` is a computer name in a network and is not a perfect name, despite being used by a few providers on their Web UI. `subdomain` is problematic/misleading since for example `a.b.c.com` is a subdomain of `b.c.com`, despite the domain being `c.com`; plus `@` or `*` are not really *subdomains*. The technical DNS name for this left part for a certain domain is `owner`, and we should use it to avoid confusion.

- [ ] Rename JSON parameter in all docs/ documents
- [ ] Rename with retro-compatibility the JSON field host in the code

**Comment by Peronia** [comment]
Well, I think `owner `is not really better than `host`. I agree with you, `host `have nothing todo with this parameter. But in my view `owner `is very technically. In my case I have a lot of confusion even when I found that issue, see [here](https://github.com/qdm12/ddns-updater/discussions/648).
I would suggest a name like `prefix`/`domainprefix` or `subpart`. Yeah I know this terms are not 100% correct, but my case is about understanding. And I agree also with you that `subdomain` can be misleading.
I could add a part at the readme that add more explanation, when you want I can open a PR.

**Comment by qdm12** [comment]
Why not otherwise have domain accept forms such as `*.domain.com`, `domain.com` and `abc.domain.com`, and remove (keep it for retro compat) the `host` field? 🤔

**Comment by Peronia** [comment]
Well, thats the best way of understanding. But is this technically possible? I know you are the maintainer so you don't suggest things that won't work I think. Do we need this `host`/`owner` value as a seperate info?

**Comment by Peronia** [comment]
Okay, got it. But why remove the documentation? Then we have an undocumentated field, that is not very nice. I would suggest to move the documentation to another plac, like archive or something like that.

**Comment by qdm12** [comment]
Because the code would still be functional with the older host field, and I hope we wouldn't need it going forward. Older documentation can still be accessed by accessing release tagged trees on github (or specific commits). If people already using the program can migrate to the newer format, that's also better for a smoother migration to a v3 release 😉

**Comment by Peronia** [comment]
I'm still not convinced about having an undocumented field, but it's not my project, I would solve it differently.
The github tree thing sounds more complicated, I'm not familiar with it anyway.

**Comment by qdm12** [comment]
1. 55d8c0d7030c657394653e814ed8efa5ca33fc13 added versioned readme+docs/ links to the readme
2. 32fafeca95473b608931522cce643158bc4ad6b8 `host` renamed to `owner` in documentation, code, and config.json. This is retro-compatible with the JSON `host` field key still.
3. 07d7645d787a81e3a6c5ee52b9ec3ccf65a4c2ea both `host` and `owner` removed in favor of getting the owner and "*eTLD+1*" from the domain field value, using golang.org/x/net/publicsuffix and a bit of string manipulation logic. This is still retro-compatible with both the `host` and `owner` JSON config field keys, which takes precedence if set to a non empty string.

Closing this since all these points should resolve this 😉
