### ISSUE TITLE
Maintenance: validate domain strings for all providers

### ISSUE THREAD

**Issue by qdm12** [qdm12/ddns-updater#626]
All domain strings are not validated for now. It would be good to check at a global scope the domain is

- empty
- a valid fqdn (without trail dot)

Some providers only use a host and the domain json value can be the empty string (constant value in the code), for example duckdns the domain is always duckdns.org. goip.de can have the domain empty, which defaults to goip.de, but it can also be set for example to goip.it.

**Comment by CyberAustin** [comment]
I'm taking a stab at this right now. Mostly got it working, just need to get the code to my dev machine at home so I can run all the linting and formatting.

**Comment by qdm12** [comment]
Awesome (no pressure either)
You can probably run it within the development container (see .devcontainer directory) if you have Docker and VSCode installed, that's what I use (from a directory in WSL2 on windows)

**Comment by CyberAustin** [comment]
Yeah, I use your include dev container. It's just that I'm at work and only have access to limited resources during work hours.

**Comment by CyberAustin** [comment]
PR created: https://github.com/qdm12/ddns-updater/pull/638
