### ISSUE TITLE
Feature request: Look up Cloudflare zone ID

### ISSUE THREAD

**Issue by yorickdowne** [qdm12/ddns-updater#632]
1. What's the feature?

Allow users to specify a token with read access to all zones, instead of the CloudFlare zone ID: zone ID would be automatically fetched for the user.

This would be optional. If zone ID is given, use it; if not, attempt to look it up by using `zone_token` (also optional) or, if that does not exist, by `token`.

For this to work, either `zone_token` has to have read access to all zones, specifically `Zone.Zone:Read` and `Zone.Zone Settings:Read`, or `token` needs to have those permissions as well as `Zone.DNS:Edit` for all zones.

**Comment by qdm12** [comment]
Interesting suggestion still! 👍 
But yes, maybe a bit convoluted 😉 Thanks 💯
