### ISSUE TITLE
Google Domains Support?

### ISSUE THREAD

**Issue by msrlrocket** [qdm12/ddns-updater#64]
Hey, would it be possible to get Google Domains support? I have heard its incredibly similar to NO-IP. Thank you very much!

**Comment by qdm12** [comment]
Hello, I've made code changes for it, their API is indeed (scarily) almost the same as NoIP 😄 

Can you please try it using the image `qmcgaw/ddns-updater:google` with the documentation [here](https://github.com/qdm12/ddns-updater/tree/google) and let me know if it works for you?

If the image is unavailable, please wait until [the Docker build finishes on Github](https://github.com/qdm12/ddns-updater/runs/723690076?check_suite_focus=true). It's also only available for amd64 cpu architectures for now, let me know if you need it for something else.

Thanks!

**Comment by msrlrocket** [comment]
Works. Thank you! Any idea what its doing when it stalls on Reading history from database? it hangs with my cloudflare settings

**Comment by msrlrocket** [comment]
Nevermind, figured it out! Thank you again.

**Comment by qdm12** [comment]
Are you sure? I made a rather big refactoring so maybe it's an issue on my side!

**Comment by qdm12** [comment]
Just a little note, the version from yesterday is bugged, please pull the `:latest` Docker image (building [here](https://github.com/qdm12/ddns-updater/runs/724822922?check_suite_focus=true)) which contains the fix. Thanks!
