### ISSUE TITLE
Bug: Healthcheck unhealty - Cloudflare - Successful IP change

### ISSUE THREAD

**Issue by marvintnk** [qdm12/ddns-updater#652]
**TLDR**: *The container health check states unhealty, although the IP gets changed succesfully.*

1. Is this urgent: No
3. DNS provider(s) you use: Cloudfare
4. Program version: version latest built on 2024-02-13T10:44:47.174Z (commit 6a6b1a8)
5. What are you using to run the container: docker-compose
6. Extra information: Maybe related to #556 . I already repulled latest, but nothing changed.

Logs:

```
2024-02-16T14:21:47Z ERROR program is unhealthy: lookup IP addresses do not match: 
```

Configuration file:

```
{
  "settings": [
    {
      "provider": "cloudflare",
      "zone_identifier": "05abbb75eccbe510f44e12c3ab7fd1fd",
      "domain": "my-domain.de",
      "host": "@",
      "ttl": 600,
      "token": "supersecrettoken",
      "ip_version": "ipv4"
    }
  ]
}
```

Host OS: Ubuntu 22.04

![image](https://github.com/qdm12/ddns-updater/assets/101425121/24e3f2cf-5f1c-4f94-b97f-0fd6a5c48140)

**Comment by qdm12** [comment]
Are you using Cloudflare proxy? If so you need to turn on `"proxied": true`.
That's how it looks like, given it says in the UI `4m39s ago`, so I guess it retries to update very 5 minutes.

**Comment by marvintnk** [comment]
Yes, that was it 💯 Thank you very much :)
