### ISSUE TITLE
Cloudflare `key "" does not match regex "^[a-zA-Z0-9]+$"`

### ISSUE THREAD

**Issue by ThomasHineXYZ** [qdm12/ddns-updater#705]
**TLDR**: *Describe your issue in a one liner here*

1. Is this urgent: Yes
2. DNS provider(s) you use: N/A
3. Program version: ae4ab39

4. What are you using to run the container: Docker, through Unraid Community Apps.
5. Extra information (optional)

Logs:

```log
========================================
========================================
============= ddns-updater =============
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version latest built on 2024-04-29T14:30:33.184Z (commit ae4ab39)

🔧 Need help? https://github.com/qdm12/ddns-updater/discussions/new
🐛 Bug? https://github.com/qdm12/ddns-updater/issues/new
✨ New feature? https://github.com/qdm12/ddns-updater/issues/new
☕ Discussion? https://github.com/qdm12/ddns-updater/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2024-04-30T01:08:19-07:00 ERROR key is not valid: key "" does not match regex "^[a-zA-Z0-9]+$"
```

Configuration file (**remove your credentials!**):

```json
N/A
```

Host OS: Unraid 6.12.6

This was running correctly on the previous commit of this. My config file hasn't changed since August 2023.

**Comment by ThomasHineXYZ** [comment]
For now I'm going to pin the version I am hosting to `v2,6` instead of `latest`.

**Comment by qdm12** [comment]
Please share your config, are you using the email field? If so you must set the key field as well. That was previously a bug (AFAIK) not validating the key field.

**Comment by ThomasHineXYZ** [comment]
It has been running just fine locked on v2.6 since my previous message last week. So it must be some change between release v2.6 and master branch.

**Comment by qdm12** [comment]
Remove the email key. As per the documentation docs/Cloudflare.md if you set an email, you're also expected to set a key. There is no need to set an email for the other authentication methods.
