### ISSUE TITLE
Could not update ip address on godaddy and error "show HTTP status is not valid: 403: Authenticated user is not allowed access"

### ISSUE THREAD

**Issue by Leoson0109** [qdm12/ddns-updater#707]
Could not update ip address on godaddy and error "show HTTP status is not valid: 403: Authenticated user is not allowed access"

**TLDR**: *Describe your issue in a one liner here*

1. Is this urgent: Yes
2. DNS provider(s) you use: N/A
3. Program version:Docker
4. What are you using to run the container: docker-compose
5. Extra information (optional)

Logs:

```
2024-05-01T15:02:27.406092772Z | stdout | 2024-05-01T15:02:27Z [91mERROR[0m HTTP status is not valid: 403: Authenticated user is not allowed access
-- | -- | --
2024-05-01T15:02:26.816464273Z | stdout | 2024-05-01T15:02:26Z [36mINFO[0m Updating record [domain: elmostation.com \| host: @ \| provider: godaddy \| ip: ipv4] to use 42.2.41.218
2024-05-01T15:02:26.816236503Z | stdout | 2024-05-01T15:02:26Z [36mINFO[0m ipv4 address of elmostation.com is 112.118.68.250 and your ipv4 address  is 42.2.41.218
2024-05-01T15:02:26.457594503Z | stdout | 2024-05-01T15:02:26Z [36mINFO[0m [http server] listening on :8000
2024-05-01T15:02:26.457453936Z | stdout | 2024-05-01T15:02:26Z [36mINFO[0m [backup] disabled
2024-05-01T15:02:26.456761051Z | stdout | 2024-05-01T15:02:26Z [36mINFO[0m [healthcheck server] listening on 127.0.0.1:9999
2024-05-01T15:02:26.456350062Z | stdout | 2024-05-01T15:02:26Z [36mINFO[0m Reading history from database: domain elmostation.com host @ ipv4
2024-05-01T15:02:26.277442332Z | stdout | 2024-05-01T15:02:26Z [36mINFO[0m Found single setting to update record
2024-05-01T15:02:26.277368767Z | stdout | 2024-05-01T15:02:26Z [36mINFO[0m reading JSON config from environment variable CONFIG
```

Configuration file (**remove your credentials!**):

lastest

```json
{"settings":[{"provider":"godaddy","domain":"elmostation.com","host":"@","key":"key","secret":"secret","ip_version":"ipv4","ipv6_suffix":""}]}
```

Host OS: docker

**Comment by qdm12** [comment]
Check your key and secret have the permission to edit the dns record for that domain

`403: Authenticated user is not allowed access` os the error message coming from Godaddy directly, highlighting you authenticated correctly (so unlikely a ddns-updater bug), but it has not the permission to do the change.

**Comment by ChristianChoi** [comment]
FYI, I'm experiencing the same issue while tring to add a new host/subdomain to my existing godaddy configuration that used to work.
I have also tried creating a new API key+secret in GoDaddy, but still getting the same error.
Also, I don't see anywhere in GoDaddy's developer portal where permissions can be modified for an API key.

**Comment by teopost** [comment]
Starting from May 1st, I'm getting the same error.
I sent an email to support and they replied with this:

```
Hi,

We have recently updated the account requirements to access parts of our production Domains API. As part of this update, access to these APIs are now limited:

Availability API: Limited to accounts with 50 or more domains
Management and DNS APIs: Limited to accounts with 10 or more domains and/or an active Discount Domain Club plan.
If you have lost access to these APIs, but feel you meet these requirements, please reply back with your account number and we will review your account and whitelist you if we have denied you access in error.

Please note that this does not affect your access to any of our OTE APIs.

If you have any further questions or need assistance with other API questions, please reach out.

Regards,

API Support Team
```

**Comment by qdm12** [comment]
Oh that sucks. Let me codify this in case a 403 status is received.

**Comment by qdm12** [comment]
Thanks @teopost your comment is linked in the code from commit d3541da8124970897e3c17c744207156663a79a6

If you get a 403 status with that particular error message, it's now logging to check your comment. Closing this as resolved.

**Comment by kayaozalp** [comment]
Just seen this error pop-up after an IP change. Spent an half an hour on the phone with customer support, most of it trying to explain what an API is, to finally being told to email api@godaddy.com
I suspect I will receive the exact same message as above.
Quoting from my email to them: "Making this change, for a paid in advance service, I find it unethical, and making the change unannounced to the users impacted is unprofessional."

I do not expect anything to come-out from this, besides moving to a different domain provider.

**Comment by gr33k** [comment]
I'll refrain from making rude comments regarding godaddy...but this is quite unfortunate. With this in effect, does this make this tool 'useless' unless you have their minimum required domains (I assume that is the sad case)?

**Comment by ChristianChoi** [comment]
This tool is not useless at all, but GoDaddy is useless. Personally, I switched to Cloudflare DNS within 5minutes, and I suggest you do the same (or any other DNS service than GoDaddy)

**Comment by BH1SCW** [comment]
I also switched to Cloudflare,  everything works well now, shit GoDaddy

**Comment by SquadCraftFTW** [comment]
I just got this domain today so I have to wait before switching :/
