### ISSUE TITLE
Working QNAP Setup

### ISSUE THREAD

**Issue by Araminta** [qdm12/ddns-updater#708]
After a couple of hours fiddling around with this, I finally figured out how to get this working in Container Station on my QNAP NAS. I'm submitting this for reference in case anyone else needs help.

My Environment:
QNAP TS453-Pro
Firmware: QTS 5.1.6.2722
Container Station: 3.0.6.833

My Steps:
1. Create a directory called 'ddns-updater' in the root of the Container share.
2. Inside the 'ddns-updater' folder, I created two directories: 'app' and 'data'.
3. Created a config.json and updates.json file in the 'data' directory (I used FileZilla to upload)
4. CHMOD the config.json file to 400. If that doesn't work, try 440, since 'Container Station' installs and runs as the admin user by default (even if 'admin' is disabled).
5. Pulled up the docker-compose.yml from the root of this repository.
6. In Container Station, I went to Applications > Create 
7. In the application name, I typed 'ddns-updater'.
8. Copied and pasted the YAML code into the window.
9. Changed the 'volumes' path in the YAML code to /share/CACHEDEV1_DATA/Container/ddns-updater:/updater/data
10. Started the container.

Notes:
In the YAML file, 'network_mode: bridge' did not automatically select bridged mode, so I edited the container to set this.
I also edited the container to change the restart setting to restart "unless stopped".

Hope this is helpful for someone trying to set this up on QNAP's weird flavor of Linux.

**Comment by qdm12** [comment]
Thanks, I referenced your issue in the readme's setup/container section.
