### ISSUE TITLE
Bug: Self-hosted healthchecks.io does not work with additional paths

### ISSUE THREAD

**Issue by Laptop765** [qdm12/ddns-updater#721]
**TLDR**: *Describe your issue in a one liner here*

1. Is this urgent: No
2. DNS provider(s) you use: N/A
3. Program version:

    

    `Running version latest built on 2024-05-06T11:16:06.246Z (commit 542e895)`

4. What are you using to run the container: docker-compose
5. Extra information (optional)

Self-hosted instances of healthchecks.io may have a ping url of the form `${BASE_URL}/ping/${UUID}` which doesn't work with the implementation in 937a249ffac9c7b498bcf7b90936f1228a049771. I'm working on a PR to add this functionality.

**Comment by RubenHCCH** [comment]
I had the same problem, I simply added the path `/ping` in `HEALTH_HEALTHCHECKSIO_BASE_URL`. Maybe documenting this is enough, and with this it is not necessary to add a new environment variable.

**Comment by Laptop765** [comment]
Oh that's much simpler, I didn't think to try that 😅

**Comment by Laptop765** [comment]
Appending `/ping` to `HEALTH_HEALTHCHECKSIO_BASE_URL` worked for me, too. Going to close this and my PR 🙂
