### ISSUE TITLE
Bug: Previous IPs NOT in reverse chronological order

### ISSUE THREAD

**Issue by petanck** [qdm12/ddns-updater#730]
The list of previous IP addresses starts with the oldest, then the next oldest...whereas the expectation is that it is in reverse chronological order so that you can see the previous IP address (before the last change) and the one before that.

1. Is this urgent: No
2. DNS provider(s) you use: Cloudflare
3. Program version: v2.6.0 (docker)
4. What are you using to run the container: docker-compose
5. Extra information (optional)
![Screenshot 2024-05-25 132701](https://github.com/qdm12/ddns-updater/assets/151444936/a080abf4-e97a-4549-baca-64f122b6565a)

Here's a redacted copy of my updates.json showing that the previous IP address showing in the webpage are the oldest (from August 2023) not the newest:

[updates.json](https://github.com/qdm12/ddns-updater/files/15443148/updates.json)

**Comment by qdm12** [comment]
Indeed, thanks for reporting this! It was silly me who wrongly coded the reversion of IP order, my bad!
