### ISSUE TITLE
Help: I'm getting "domain is not valid"

### ISSUE THREAD

**Issue by cc13com** [qdm12/ddns-updater#754]
**TLDR**: *After starting my ddns-updater docker container I'm getting the error "domain is not valid"*

1. Is this urgent: No
2. DNS provider(s) you use: GoIP.de
3. Program version: Running version latest built on 2024-06-27T13:12:29.849Z (commit 07d7645)

4. What are you using to run the container: docker-compose up -d
5. Extra information (optional)

Logs:

```
Running version latest built on 2024-06-27T13:12:29.849Z (commit 07d7645)

🔧 Need help? https://github.com/qdm12/ddns-updater/discussions/new

🐛 Bug? https://github.com/qdm12/ddns-updater/issues/new

✨ New feature? https://github.com/qdm12/ddns-updater/issues/new

☕ Discussion? https://github.com/qdm12/ddns-updater/discussions/new

💻 Email? quentin.mcgaw@gmail.com

💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12

2024-06-27T14:30:24Z INFO Settings summary:

├── HTTP client

|   └── Timeout: 10s

├── Update

|   ├── Period: 5m0s

|   └── Cooldown: 5m0s

├── Public IP fetching

|   ├── HTTP enabled: yes

|   ├── HTTP IP providers

|   |   └── all

|   ├── HTTP IPv4 providers

|   |   └── all

|   ├── HTTP IPv6 providers

|   |   └── all

|   ├── DNS enabled: yes

|   ├── DNS timeout: 3s

|   └── DNS over TLS providers

|       └── all

├── Resolver: use Go default resolver

├── Server

|   ├── Listening address: :8000

|   └── Root URL: /

├── Health

|   └── Server listening address: 127.0.0.1:9999

├── Paths

|   ├── Data directory: /updater/data

|   └── Config file: /updater/data/config.json

├── Backup: disabled

└── Logger

    ├── Level: info

    └── Caller: hidden

2024-06-27T14:30:24Z INFO reading JSON config from file /updater/data/config.json

2024-06-27T14:30:24Z ERROR validating provider specific settings: domain is not valid: "MyDomain.goip.de" must be "goip.de" or "goip.it"

2024-06-27T14:30:24Z INFO Shutdown successful

```

Configuration file (**remove your credentials!**):

```
{
  "settings": [
    {
      "provider": "goip",
      "domain": "MyDomain.goip.de",
      "username": "MyUsername",
      "password": "MyPassword",
      "provider_ip": true,
      "ip_version": "",
      "ipv6_suffix": ""

    }
  ]
}
```

Host OS: Debian LXC on Proxmox

**Comment by qdm12** [comment]
This is due to recent commit 07d7645d787a81e3a6c5ee52b9ec3ccf65a4c2ea, I have pushed 158fed7c51250fbc3131cf03db231d2ce1cdfa51 to hopefully fix this, can you pull the latest image and try again?

For details, the reason is `goip.de` and `goip.it` are effective TLDs ("eTLDs") which I didn't know, so I was expecting `goip.de` to be the domain for `MyDomain.goip.de` and `MyDomain` to be the owner/host. In reality, the domain is `MyDomain.goip.de` and the owner/host is the root domain `@`.

**Comment by cc13com** [comment]
Hi @qdm12 , after pulling the latest container it works. Thanks.

Just one additional information: Before GoIP I tried it with DuckDNS with the same issue. But since GoIP is working for me I will not switch to DuckDNS. ;-)

**Comment by qdm12** [comment]
Funnily enough, I also fixed duckdns right after goip.de in c345a788e326b15419ffb0acc8bb613cfc6424f6 (which has the same problem as goip.de: duckdns.org is an eTLD). I appreciate you letting me know this, because I could definitely had missed out on it!
