### ISSUE TITLE
Issues getting DDNS to work. 

### ISSUE THREAD

**Issue by msrlrocket** [qdm12/ddns-updater#76]
I have discovered while doing a docker-compose up it will hang on 

`Reading history from database: domain URL.X host @`

This happens when I do not have the correct HOME IP set within namecheap on my A record before DDNS-Updater boots up. Occasionally it will come up with the IP being off and will successfully change it. 

After its running, I can get to the web interface and see that it successfully changed it. If my IP changes however, it doesn't look like its being recorded over on namecheap. All I get is:

```
 2020-05-31T04:35:17.344Z	WARN	unhealthy: lookup IP address of msrl.cc is 73.169.x.x instead of 73.169.x.x
ddns    | 2020-05-31T04:36:17.670Z	WARN	unhealthy: lookup IP address of msrl.cc is 73.169.x.x  instead of 73.169.x.x
ddns    | 2020-05-31T04:37:18.059Z	WARN	unhealthy: lookup IP address of msrl.cc is 73.169.x.x instead of 73.169.x.x
```
It gives me the warning but it doesn't update it. I can then do a docker-compose and it either goes through and changes it or hangs. I have no idea at this point.

**Comment by qdm12** [comment]
Hello there, thanks so much for pointing this out to me 👍 

I just fixed it (an asynchronous error, it was exiting silently its update loop directly at the start, silly me!).

I tried it with a namecheap record, setting to `127.0.0.1` and it works now.

Please re-pull (once [the build is done](https://github.com/qdm12/ddns-updater/runs/724822922?check_suite_focus=true)) 😉 

Let me know if it works out for you! I'll make a release+docker tag if so as I'm (yet again) about to add a lot of changes for an interactive web ui.
