### ISSUE TITLE
Bug: ERROR validating domain

### ISSUE THREAD

**Issue by JohnBardoe** [qdm12/ddns-updater#761]
**TLDR**: Can't put several domains for namecheap

1. Is this urgent: No
2. DNS provider(s) you use: namecheap
3. Program version: 2.7.0 built on 2024-06-26T19:34:57.277Z (commit d37f057)
4. What are you using to run the container: docker-compose
5. Extra information (optional)

Logs:

```log
2024-07-06T03:20:30+04:00 INFO reading JSON config from file /updater/data/config.json
2024-07-06T03:20:30+04:00 ERROR validating domain: domain has invalid character ',' at offset 14
2024-07-06T03:20:30+04:00 INFO Shutdown successful
```

Configuration file:
```json
{
    "settings": [
        {
            "provider": "namecheap",
            "domain": "git.lalala.ing,lalala.ing",
            "password": "..."
        }
    ]
}
```

**Comment by qdm12** [comment]
You are using the wrong version, if you want to specify multiple owners (aka hosts) for the same domain in the domain field as you did, use the latest version (`qmcgaw/ddns-updater`). Otherwise the relevant readme for v2.7.0 is linked at the top of the master branch readme.

**Comment by JohnBardoe** [comment]
this IS v2.7.0

**Comment by qdm12** [comment]
Please re-read my comment carefully
