### ISSUE TITLE
Feature request: add do.de (Domain-Offensive)

### ISSUE THREAD

**Issue by Runortyx88** [qdm12/ddns-updater#770]
Einrichtung für alle FRITZ!OS-Version 7 oder höher

DynDNS-Anbieter: Benutzerdefiniert
Update-URL: https://ddns.do.de/?myip=<ipaddr>
Domainname: Name der betreffenden (Sub-)Domain (empfehlenswert ist hier der Hostname, wo IPv4 und IPv6-Adresse aktiviert ist)
Benutzername: 
Kennwort: 

Hinweis: Je nachdem welche Adressen in der DNS aktualisiert werden sollen, kann sich die Update-URL unterscheiden.

IPv4-Adresse: https://ddns.do.de/?myip=<ipaddr>
IPv4 und IPv6-Adresse: https://ddns.do.de/?myip=<ipaddr> https://ddns.do.de/?myip=<ip6addr>
IPv6-Adresse: https://ddns.do.de/?myip=<ip6addr>
IPv4-Adresse und IPv6-Präfix: https://ddns.do.de/?myip=<ipaddr> https://ddns.do.de/?ip6lanprefix=<ip6lanprefix>
IPv6-Präfix: https://ddns.do.de/?ip6lanprefix=<ip6lanprefix>
IPv4-Adresse, IPv6-Adresse und IPv6-Präfix: https://ddns.do.de/?myip=<ipaddr> https://ddns.do.de/?myip=<ip6addr>&ip6lanprefix=<ip6lanprefix>
IPv6-Adresse und IPv6-Präfix (meist DS-Lite-Anschlüsse): https://ddns.do.de/?myip=<ip6addr>&ip6lanprefix=<ip6lanprefix>

**Comment by qdm12** [comment]
Duplicate of #310 please subscribe to that one instead 😉
