### ISSUE TITLE
Using 1 provider "Cloudflare". When ran, it registers as provider "Dreamhost

### ISSUE THREAD

**Issue by msrlrocket** [qdm12/ddns-updater#79]
**TLDR**: *Describe your issue in a one liner here*

1. Is this urgent?

    - [ ] Yes
    - [x] No

2. What DNS service provider(s) are you using?

    - [x] Cloudflare
    - [ ] DDNSS.de
    - [ ] DNSPod
    - [ ] Dreamhost
    - [ ] DuckDNS
    - [ ] GoDaddy
    - [ ] Google
    - [ ] Infomaniak
    - [ ] Namecheap
    - [ ] NoIP

3. What's the version of the program?

    **See the line at the top of your logs**

    `Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)`

4. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information

Logs:

```log

```

Configuration file (**remove your credentials!**):

```json

```

Host OS:

**Comment by qdm12** [comment]
Thanks a lot for reporting this! It was just the wrong display string, I fixed it now. No worry, nothing went to Dreamhost :wink:
