### ISSUE TITLE
Request: No-IP

### ISSUE THREAD

**Issue by SuperJakish** [qdm12/ddns-updater#8]
Any chance of getting No-IP's service added? They have a Linux based app, but I'm not able to get it working and it would be awesome to add it to the docker environment.

The app and some support is available here: https://www.noip.com/download

**Comment by qdm12** [comment]
Hi there,

I am almost done implementing it, but would you mind sending me what you get in your browser when you enter [http://username:password@dynupdate.no-ip.com/nic/update?hostname=mytest.testdomain.com](http://username:password@dynupdate.no-ip.com/nic/update?hostname=mytest.testdomain.com) (replace with your username, password and hostname)? The documentation is quite unclear about the response and I would like to treat the success/errror properly. 

Thanks

**Comment by qdm12** [comment]
Hi again,

I merged NoIP, so it should be available in a few minutes.

```sh
docker pull qmcgaw/ddns-updater
```

Example configuration:

```json
{
    "settings": [
        {
            "provider": "noip",
            "domain": "example.com",
            "host": "@",
            "ip_method": "provider",
            "email": "youremail@email.com"
            "password": "yourpassword"
        }
    ]
}
```

Let me know if it works or what error messages it gives 😄

**Comment by SuperJakish** [comment]
Hey! Thanks for the swift response!

Here is the response from http://username:password@dynupdate.no-ip.com/nic/update?hostname=mytest.testdomain.com with my information entered. I x'd out my IP address, but this was the format of the response.
`
nochg xxx.xxx.xxx.xxx

`
Of note, noip can use either the user name or email address for the username field in the URL above - I tested both variations with the same output.

Now, I've appended my config.json file with the new settings for NoIP, stopped the container, did a `docker system prune` to get rid of the old image, ran `docker-compose up -d` and get the following output from the logs:
```
ddns_updater    | {"level":"Warning","message":"Provider noip not recognized","time":"2019-05-23T11:51:46.372129695Z","node":0}
ddns_updater    | {"level":"Info","message":"Found 1 settings to update records","time":"2019-05-23T11:51:46.372228243Z","node":0}
ddns_updater    | {"level":"Info","message":"Reading history from database for domain and host: <MY_CLOUDFLARE_DOMAIN> @","time":"2019-05-23T11:51:49.084252063Z","node":0}
ddns_updater    | {"level":"Info","message":"Web UI listening on 0.0.0.0:8000","time":"2019-05-23T11:51:49.092097157Z","node":0}
```

It should be said that for (reasons) I'm trying to update the ddns records for both cloudflare _and_ NoIP. For giggles, I removed the cloudflare settings and get the following log output:
```
ddns_updater    | {"level":"Warning","message":"Provider noip not recognized","time":"2019-05-23T12:16:25.984580357Z","node":0}
ddns_updater    | {"level":"Fatal","message":"no settings found in config.json","time":"2019-05-23T12:16:25.984663143Z","node":0}
```

I tried pulling the noip branch in my docker-compose file by specifying `image: qmcgaw/ddns-updater:noip`, but that didn't work because it said the image couldn't be found. I'm still new to Docker and I'm not sure that this is the right way to specify branches.

Thanks very much for your support in this!

**Comment by qdm12** [comment]
Thanks for all the info!

There is a Git branch `noip` but no Docker tag `noip` :smile:

I believe you still have an older image, try:

```sh
docker-compose pull
docker-compose up -d --force-recreate
```

And it should work!

**Comment by SuperJakish** [comment]
Alrighty - the pulls worked and I got the new image. Thanks for that tip!

It looks like i'm getting a 401 error in the health check. Here is the log:
```
ddns_updater    | {"level":"Info","message":"Found 2 settings to update records","time":"2019-05-23T13:11:29.309697108Z","node":0}
ddns_updater    | {"level":"Info","message":"Reading history from database for domain and host: <MY_CLOUDFLARE_DOMAIN> @","time":"2019-05-23T13:11:37.072386458Z","node":0}
ddns_updater    | {"level":"Info","message":"Reading history from database for domain and host: <MY_NOIP_DOMAIN> @","time":"2019-05-23T13:11:37.072551831Z","node":0}
ddns_updater    | {"level":"Info","message":"Web UI listening on 0.0.0.0:8000","time":"2019-05-23T13:11:37.072656765Z","node":0}
ddns_updater    | {"level":"Warning","message":"{\"domain\":\"<MY_NOIP_DOMAIN>\",\"host\":\"@\",\"provider\":\"noip\"}: Failure (HTTP status 401) at 2019-05-23 13:11:37 UTC; ","time":"2019-05-23T13:11:37.466717691Z","node":0}
ddns_updater    | {"level":"Warning","message":"Responded with error to healthcheck: {\"domain\":\"<MY_NOIP_DOMAIN>\",\"host\":\"@\",\"provider\":\"noip\"}: Failure (HTTP status 401) at 2019-05-23 13:11:37 UTC; ","time":"2019-05-23T13:11:38.29968914Z","node":0}
```

**Comment by qdm12** [comment]
Hi again,

It might work now, as I was sending `username:password` without any encoding (although it's meant to be allowed). I now changed it to the recommended base64 encoding. Can you please try again?

```sh
docker pull qmcgaw/ddns-updater
docker-compose down
docker-compose up
```

Thanks!

**Comment by SuperJakish** [comment]
Here is what I did:
```
docker-compose stop ddns_updater
docker system prune
docker-compose pull ddns_updater
docker-compose up -d --force-recreate ddns_updater
docker-compose logs -f ddns_updater
```

It looks like the 401 error is still occurring:
```
ddns_updater    | {"level":"Info","message":"Found 2 settings to update records","time":"2019-05-23T13:53:12.146486008Z","node":0}
ddns_updater    | {"level":"Info","message":"Reading history from database for domain and host: <MY_CLOUDFLARE_DOMAIN> @","time":"2019-05-23T13:53:12.817677347Z","node":0}
ddns_updater    | {"level":"Info","message":"Reading history from database for domain and host: <MY_NOIP_DOMAIN> @","time":"2019-05-23T13:53:12.822620763Z","node":0}
ddns_updater    | {"level":"Info","message":"Web UI listening on 0.0.0.0:8000","time":"2019-05-23T13:53:12.822828422Z","node":0}
ddns_updater    | {"level":"Warning","message":"{\"domain\":\"<MY_NOIP_DOMAIN>\",\"host\":\"@\",\"provider\":\"noip\"}: Failure (HTTP status 401) at 2019-05-23 13:53:12 UTC; ","time":"2019-05-23T13:53:13.31227443Z","node":0}
```

**Comment by qdm12** [comment]
Could you try with `curl` the following:

```sh
curl --header "Authorization: Basic username:password" --header "User-Agent: DDNS-Updater quentin.mcgaw@gmail.com" https://dynupdate.no-ip.com/nic/update?hostname=yourhostname.com
```

What does it repond?

**Comment by SuperJakish** [comment]
Ah HAH! I ran the `curl` with my email address as the _username_ and received `badauth`, but when I changed my email address to my NoIP username it worked and responded with `nochg xxx.xxx.xxx.xxx`.

I went ahead and changed the "email" in the settings.json file to my username and received an error that the email address is an invalid format.
`ddns_updater    | {"level":"Warning","message":"invalid email format for settings {\"domain\":\"<MY_NOIP_DOMAIN>\",\"host\":\"@\",\"provider\":\"noip\"}","time":"2019-05-23T14:52:19.865626641Z","node":0}`

**Comment by qdm12** [comment]
Haha ok I will change it to `"username"` instead of `"email"` in that case 😄  Thanks for debunking that bug... bad bad NoIP...

**Comment by SuperJakish** [comment]
I don't mean to be a bother, but I'm getting a "username cannot be empty" warning now.
```
ddns_updater    | {"level":"Warning","message":"username cannot be empty for settings {\"domain\":\"<MY_NOIP_DOMAIN>\",\"host\":\"@\",\"provider\":\"noip\"}","time":"2019-05-23T16:34:10.934899384Z","node":0}
```

I pulled the latest commit, added a `"username": "<MY_NOIP_USERNAME>",` entry to the `config.json` entry, and removed the `"email"` entry. Thoughts?

**Comment by qdm12** [comment]
Oh yes forgot to update the readme! will do soon.

It's now `"username"` as the email doesn't work.

**Comment by SuperJakish** [comment]
Right - my `config.json` now looks like:
```
        {
            "provider": "noip",
            "domain": "<MY_NOIP_DOMAIN",
            "host": "@",
            "ip_method": "provider",
            "username": "<NOIP_USER>",
            "password": "<NOIP_PASS>"
        }
```
and I'm getting this warning in the log:
```
ddns_updater    | {"level":"Warning","message":"username cannot be empty for settings {\"domain\":\"<MY_NOIP_DOMAIN>\",\"host\":\"@\",\"provider\":\"noip\"}","time":"2019-05-23T19:11:06.018961665Z","node":0}
```
I've done the 
```
docker-compose stop ddns_updater
docker system prune
docker-compose pull ddns_updater
docker-compose up -d --force-recreate ddns_updater
docker-compose logs -f ddns_updater
```
just to make sure I have the latest version.

**Comment by CygnusHyoga** [comment]
Hi qdm12,

I've the same problem with NoIP, my config.json:

```
{
    "settings": [{
            "provider": "noip",
            "host": "@",
	    "domain": "xxxx",
	    "username": "xxx",
            "password": "xxx",
            "ip_method": "opendns",
            "delay": 300
        }
    ]
}
```

Error:


{"level":"Warning","message":"username cannot be empty for settings {\"domain\":\"xxx\",\"host\":\"@\",\"provider\":\"noip\"}","time":"2019-06-07T19:56:31.270552014Z","node":0}

Thanks!

**Comment by qdm12** [comment]
Hi @SuperJakish and @CygnusHyoga

Sorry I did not reply/fix it earlier. I found the problem, I forgot to update the JSON parsing mechanism. I'll fix it tomorrow morning (in Europe here) and report back.

Thanks!

**Comment by CygnusHyoga** [comment]
Hi again qdm12! Thanks for the changes!

Now username it's recognized fine, but I get a 401. I tried with noip username and with my noip associate email as username var. I tried my username/password with noip web, etc. and it's fine.


{"level":"Info","message":"Reading history from database for domain and host: xxx.ddns.net @","time":"2019-06-08T08:57:43.212216082Z","node":0}
--
  | {"level":"Info","message":"Reading history from database for domain and host: xxx.duckdns.org @","time":"2019-06-08T08:57:43.227238084Z","node":0}
  | {"level":"Info","message":"Web UI listening on 0.0.0.0:8000","time":"2019-06-08T08:57:43.300510526Z","node":0}
  | {"level":"Warning","message":"{\"domain\":\"xxx.ddns.net\",\"host\":\"@\",\"provider\":\"noip\"}: Failure (HTTP status 401) at 2019-06-08 08:57:43 UTC; ","time":"2019-06-08T08:57:44.120231608Z","node":0}

My config:

{
    "settings": [{
            "provider": "noip",
	    "host": "@",
	    "domain": "xxx.ddns.net",
	    "username": "xxx",
            "password": "xxx",
            "ip_method": "opendns"
        },
        {
            "provider": "duckdns",
            "domain": "xxxx.duckdns.org",
            "ip_method": "provider",
            "token": "xxx"
        }
    ]
}

**Comment by qdm12** [comment]
`401` means you're unauthorized. You say *it's fine*, what do you mean? Does it work or not?

If it does not work, can you try with **curl**:

```sh
curl --header "Authorization: Basic username:password" --header "User-Agent: DDNS-Updater quentin.mcgaw@gmail.com" https://dynupdate.no-ip.com/nic/update?hostname=yourhostname.com
```

by replacing your `username`, `password` and `yourhostname.com`

And see what it responds?

**Comment by CygnusHyoga** [comment]
It's not working noip from the app (duckdns is working ok). 

With curl it's working ok:

curl --header "Authorization: Basic xxx:xxx" --header "User-Agent: DDNS-Updater quentin.mcgaw@gmail.com" https://dynupdate.no-ip.com/nic/update?hostname=xxx.ddns.net
nochg 90.94.132.xxx

**Comment by CygnusHyoga** [comment]
qdm12 now its working OK from the app! Maybe something with the api from noip when I tried...sorry for the trouble.

**Comment by SuperJakish** [comment]
I can confirm this works now as well. Just a note for future folks: both the username and password fields are case sensitive.

Thanks so much for all of your work!
