### ISSUE TITLE
Discrepancy in docs/porkbun.md

### ISSUE THREAD

**Issue by kuolemaaa** [qdm12/ddns-updater#816]
**TLDR**: The example says api_key and secret_api_key but the compulsory paragraph apikey and secretapikey

1. Is this urgent: No
2. DNS provider(s) you use: porkbun

https://github.com/qdm12/ddns-updater/blob/master/docs/porkbun.md

**Comment by qdm12** [comment]
Indeed, that's fixed now, thanks! 👍

**Comment by SimonAkers** [comment]
Hi, I have also just noticed it looks like the actual API key and secret API key are backwards in the example Porkbun config.

`pk` prefix should be API key, `sk` prefix should be secret key.

1. Is this urgent: No
2. DNS provider(s) you use: Porkbun
