### ISSUE TITLE
Bug: Provider Netcup - Wildcard not working

### ISSUE THREAD

**Issue by m1dy** [qdm12/ddns-updater#820]
**TLDR**: *Netcup has no Wildcard support*
I know Wildcards work for Netcup because I'm using one right now. 

1. Is this urgent: No
2. DNS provider(s) you use: Netcup
3. Program version: 2024-09-19T14:24:22.858Z (commit c16287e)
4. What are you using to run the container: docker-compose
5. Extra information

Logs:

```
ERROR validating provider specific settings: owner cannot be "*"
```

Configuration file (**remove your credentials!**):

```
{
  "settings": [
    {
      "provider": "netcup",
      "domain": "domain.tld,*.domain.tld",
      "api_key": "KEY",
      "password": "PW",
      "customer_number": "123456",
      "ip_version": "ipv4",
      "ipv6_suffix": ""
    }
  ]
}

```

Host OS: Ubuntu Server

**Comment by qdm12** [comment]
The original author of the netcup code in particular wrote "It cannot be the wildcard". I've asked him in https://github.com/qdm12/ddns-updater/pull/361#issuecomment-2485581882 and will wait for a reply.

**Comment by m1dy** [comment]
@qdm12 Works with :pr-863 !
Thank you!

**Comment by qdm12** [comment]
PR merged, you can use the latest image from now 😉 ! Thanks for confirming!
