### ISSUE TITLE
Updating record dondominio ERROR unsuccessful result: Incorrect data

### ISSUE THREAD

**Issue by Gabiginer** [qdm12/ddns-updater#832]
**TLDR**: *Unable to update new IP*

1. Is this urgent: No
2. DNS provider(s) you use: Dondominio
3. Program version: v 2.8.1

    

    `Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)`

4. What are you using to run the container: docker-compose
5. Extra information (optional)

Logs:
```
2024-10-06T10:34:37Z INFO ipv4 address of MYDOMAIN.COM is 111.111.111.111 and your ipv4 address  is 222.222.222.222
2024-10-06T10:34:37Z INFO Updating record [domain: MYDOMAIN.COM | owner: @ | provider: dondominio | ip: ipv4] to use 222.222.222.222
2024-10-06T10:34:37Z ERROR unsuccessful result: Incorrect data
```

Configuration file (**remove your credentials!**): 

```json
{
  "settings": [
    {
      "provider": "dondominio",
      "domain": "MYDOMAIN.COM",
      "username": "MYUSER",
      "key": "DonDNS_API_KEY",
      "ip_version": "ipv4",
      "ipv6_suffix": ""
    }
  ]
}
```

Host OS: Debian

**Comment by qdm12** [comment]
You are saying you are running version `v 2.8.1` which was released on 2024-09-20 but in your logs it says `Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)` so clearly, just update the Docker image.

**Comment by madmalkav** [comment]
II’m having this exact same problem running version 2.9.0
