### ISSUE TITLE
Porkbun API Change

### ISSUE THREAD

**Issue by dawnerd** [qdm12/ddns-updater#836]
Just got an email about this

```
CRITICAL UPDATE DETAILS

Type: API Hostname Change

Old Value: [porkbun.com](https://porkbun.com/)

New Value: [api.porkbun.com](https://api.porkbun.com/)

Deadline: 2024-12-01 00:00:00 UTC
```

**Comment by esackbauer** [comment]
See also porkbun documentation, new API hostname is already active:
https://api.porkbun.com/api/json/v3/documentation#apiHost

**Comment by qdm12** [comment]
Done in 118132f238bfb93e4d9ed094d863323e5605be0c
I'll do a v2.8.2 release sometime soon (feel free to comment if you need this and it's still not done in ~mid november).

**Comment by adripo** [comment]
Hello @qdm12, I would like to kindly remind you about the upcoming API change. The deadline is December 1st, and I would appreciate it if we could have a couple of days to test it before that date. Thank you!

**Comment by adripo** [comment]
I just tested it and it works correctly. I will keep `:latest` until the new `:2` version is released. Thank you!

**Comment by qdm12** [comment]
Thanks! There is a bugfix v2.8.2 release containing this (v2 tag works, just pull the image).
