### ISSUE TITLE
Feature request: Add support for Don Dominio

### ISSUE THREAD

**Issue by fer112233** [qdm12/ddns-updater#84]
I would love to have support for Don Dominio DNS.

**Comment by qdm12** [comment]
Hello, I've added some modifications in #85 for it. Could you please try using the [documentation here](https://github.com/qdm12/ddns-updater/tree/don-dominio) and with the docker image `qmcgaw/ddns-updater:don-dominio` to see if it works for you? Thanks!

**Comment by qdm12** [comment]
Hello, have you had the chance to try it? Thanks!
