### ISSUE TITLE
Support for 'Domain Offensive' (do.de)

### ISSUE THREAD

**Issue by zysenia** [qdm12/ddns-updater#850]
1. What's the feature? a ddns service (they name it flexDNS)

2. Extra information? ddns.do.de is the update-url to update the public ip. When accessing the page you have to enter a username and also a password
For further information here's the offical page with some images from the provider: https://www.do.de/wiki/flexdns-einrichtung/

**Comment by qdm12** [comment]
Duplicate of #310 please subscribe to that one instead 😉
