### ISSUE TITLE
Bug: Gandi dns url has changed

### ISSUE THREAD

**Issue by Nichlas** [qdm12/ddns-updater#852]
**TLDR**: Gandi fails because dns url is deprecated

1. Is this urgent: Yes
2. DNS provider(s) you use: Gandi
3. Program version: 2.8.1

 
    `Running version 2.8.1 built on 2024-09-20T07:18:44.173Z (commit c16287e)`

4. What are you using to run the container: docker-compose
5. Extra information (optional)

New API URL: https://api.gandi.net/v5/livedns

`2024-11-05 17:20:44.810921+00:002024-11-05T18:20:44+01:00 ERROR HTTP status is not valid: 403: {"object": "HTTPForbidden", "cause": "Forbidden", "code": 403, "message": "Access was denied to this resource."}`

**Comment by qdm12** [comment]
What's the difference between the domain API (https://api.gandi.net/docs/domains/) and the LiveDNS API (https://api.gandi.net/docs/livedns/)?

I would prefer to go the domain API route, and check if it works for you first, before doing the livedns API which might not work for all gandi.net domains.

**Comment by Nichlas** [comment]
I'm not sure the one or the other is best, but the point is that the api endpoint in the code doesn't work, and that the endpoint should be updated.

**Comment by qdm12** [comment]
API URL updated in 46e1edb8f232ea2bd655757c35fb79764f272056 😉 
Please let me know if it works fine.
Also, side extra question, can you try it with an owner (aka host) that doesn't exist on your existing domain, to check if ddns-updater creates the record or what error you get in the logs? For example set your `"domain": "doesnotexist.yourdomain.com"`. Trying to fix this for issue #129 whilst I'm at it.
