### ISSUE TITLE
Bug: in casaOS "unhealthy" image problem

### ISSUE THREAD

**Issue by SpyrMark** [qdm12/ddns-updater#853]
**TLDR**: Can't update to latest version due to "unhealthy" status throu the CasaOS appstore

1. Is this urgent: No
2. DNS provider(s) you use: Duckdns
3. Program version: 2.6

    

    `Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)`

4. What are you using to run the container: CasaOS
5. Extra information (optional)

Logs:

```log

```

Configuration file (**remove your credentials!**):

```json

```

Host OS: CassaOS/Debian 12

**Comment by qdm12** [comment]
Try upgrading your version, this release you are running is 4 years old. If the problem persists with a newer version, please open another issue, describing what the healthcheck error is as well.
