### ISSUE TITLE
Feature request: ... DNS-O-MATIC

### ISSUE THREAD

**Issue by ghires** [qdm12/ddns-updater#88]
1. What's the feature?
Would "dns-o-matic" to be included as a provider. 
https://www.dnsomatic.com/

2. Why do you need this feature?
Have been using it for years. Would provide potential to expand your service of providers without having to create all the providers that dns-o-matic already provides.

3. Extra information?
Thanks!

**Comment by qdm12** [comment]
I'll do it during this week. Thanks for the suggestion.

For my future self, ➡️ [api docs](https://www.dnsomatic.com/docs/api)

**Comment by qdm12** [comment]
Hey I finally got the time to add support for it.

Can you please try sometime with the image `qmcgaw/ddns-updater:dnsomatic` see if it works for you? Documentation for dnsomatic is available on [this branch](https://github.com/qdm12/ddns-updater/tree/dnsomatic).

**Comment by qdm12** [comment]
Hey again, did you have time to try it out? I'll merge it in the coming days and close the issue without a reply. Thanks!
