### ISSUE TITLE
DDNS Update with Ionos

### ISSUE THREAD

**Issue by jdh1978** [qdm12/ddns-updater#882]
1. I would like to be able to use DDNS from Ionos.

2. I already have multiple domains with them and would like to just add a subdomain to point at some applications running on my home network.

https://www.ionos.com/help/domains/configuring-your-ip-address/set-up-dynamic-dns-with-company-name/?source=ionos-hc

[]

**Comment by qdm12** [comment]
See https://github.com/qdm12/ddns-updater/blob/master/docs/ionos.md
