### ISSUE TITLE
Bug: Godaddy is bad 

### ISSUE THREAD

**Issue by oozj** [qdm12/ddns-updater#91]
2020-08-06T15:21:03.055Z	ERROR	HTTP status 401 - Unauthorized : Could not authenticate API key/secret

**Comment by qdm12** [comment]
Are you sure your API secret is valid?

**Comment by jpherrell** [comment]
I'm having the same issue. I can access the API myself using Postman and the same keys. Doesn't fail if there is nothing to update, but does if there is a change.

**Comment by qdm12** [comment]
Ok I'll check, maybe they changed their API. Should be done tomorrow.

**Comment by qdm12** [comment]
Hello both, I checked and their API did not change wether to update DNS records or for authorization.

Unfortunately, I have no domain at GoDaddy anymore, can you please try

```sh
docker run -it --rm alpine:3.12
apk add curl
curl -X PUT -H "Authorization: sso-key [KEY]:[SECRET]" -H "Content-Type: application/json" -d '{"data":"127.0.01"}' "https://api.godaddy.com/v1/domains/[DOMAIN]/A/@"
exit
```

Replacing:

- `[KEY]` by your API Key
- `[SECRET]` by your API secret
- `[DOMAIN]` by your domain
- Eventually `@` by your host (or subdomain)

And see/report back the response? That should update your record to 127.0.0.1 (nothing really). That should work according to Godaddy's doc and ddns-updater *should* do the exact same.

**Comment by jpherrell** [comment]
Sorry it has taken so long for me to reply:

When I send a body of {"data":"127.0.0.1"} I get this from them:
{
    "code": "INVALID_BODY",
    "fields": [
        {
            "code": "UNEXPECTED_TYPE",
            "message": "is not a array",
            "path": "records"
        }
    ],
    "message":
"Request body doesn't fulfill schema, see details in `fields`"
}

When I send a body of
[
    {
        "data": "127.0.0.1",
        "name": "@",
        "ttl": 3600,
        "type": "A"
    }
]

it works fine.

**Comment by qdm12** [comment]
:+1: That should be it, will fix it tonight. Thanks for answering back!

**Comment by qdm12** [comment]
Actually the program already sends `[{"data":"127.0.0.1"}]` as the body, can you try with just that body?
Referring to their API documentation, precisely to https://developer.godaddy.com/doc/endpoint/domains#/v1/recordReplaceTypeName, it seems only `"data"` is required in the body of the request; `"name'` and `"type"` are given in the URL.

Sorry I have no domain with GoDaddy so I'm a bit blind sighted for debugging it.

**Comment by jpherrell** [comment]
I tried it with just [{"data": "127.0.0.1"}] and it worked as well. I'll
get the latest ddns-updater image and try another test run later today.

**Comment by qdm12** [comment]
Hey sorry for being away for a while, but is it working again perhaps? If not, what's the error log message you get? Still an authentication error? Thanks!

**Comment by jpherrell** [comment]
Sorry, it wasn't working last time I tried the latest code. Seems like it
was still an auth issue. Perhaps it's in the handling of the config string
that I'm passing to the container. Not sure.

Since I'm a developer myself, I wrote my own updater. So I haven't tried to
figure out what the issue was.

Sorry I can't be of any more help,
Jon

**Comment by qdm12** [comment]
Alright thanks for letting me know. Actually what's your script out of curiosity regarding the authorization part?
My code sets as header `Authorization: sso-key [KEY]:[SECRET]` are you using something different?

And @oozj did you manage to make it work perhaps?

**Comment by jpherrell** [comment]
My code is in Python/Django, but you'll get the point. I think we're doing
the same thing. I really think it's something I was doing setting the
parameters for the container.

    go_daddy_url = "https://api.godaddy.com/v1/domains/" +
os.environ.get('GO_DADDY_DOMAIN', '') + "/records/A/@"
    go_daddy_headers = {'Content-Type': 'application/json',
        'Authorization': 'sso-key
{0}:{1}'.format(os.environ.get('GO_DADDY_KEY', ''),
        os.environ.get('GO_DADDY_SECRET', ''))}
     body = [{"data": self.current_address}]
     response = requests.put(self.go_daddy_url,
headers=self.go_daddy_headers, json=body)

**Comment by qdm12** [comment]
Nice thanks a lot for sharing, I'll cross compare to ensure we have the same thing 😄

**Comment by qdm12** [comment]
Thanks again for sharing. It is indeed exactly the same 😄  Let's close the issue unless someones encounters the problem again. Did you have any funny characters in your key or secret perhaps?

**Comment by jpherrell** [comment]
I thought of that. Mostly alphanumeric, and nothing that would require
escaping.
